/**
 * 成就数据定义
 * 从 achievements.js 分离，便于维护和扩展
 */

// 稀有度定义
var RARITY = {
  common: { name: '普通', color: '#4CAF50', bg: '#E8F5E9' },
  rare: { name: '稀有', color: '#2196F3', bg: '#E3F2FD' },
  legendary: { name: '传说', color: '#FF9800', bg: '#FFF3E0' }
}

// 成就定义
var ACHIEVEMENTS = [
  // ===== 刷牙成就 =====
  { id: 'brush_3', icon: '🦷', title: '刷牙新手', desc: '连续刷牙3天', category: 'habit', rarity: 'common',
    condition: function(data) { return data.brushingStreak >= 3 },
    progress: function(data) { return Math.min(data.brushingStreak, 3) }, maxProgress: 3 },
  { id: 'brush_7', icon: '🥇', title: '刷牙达人', desc: '连续刷牙7天', category: 'habit', rarity: 'common',
    condition: function(data) { return data.brushingStreak >= 7 },
    progress: function(data) { return Math.min(data.brushingStreak, 7) }, maxProgress: 7 },
  { id: 'brush_30', icon: '🏆', title: '刷牙冠军', desc: '连续刷牙30天', category: 'habit', rarity: 'rare',
    condition: function(data) { return data.brushingStreak >= 30 },
    progress: function(data) { return Math.min(data.brushingStreak, 30) }, maxProgress: 30 },

  // ===== 习惯打卡成就 =====
  { id: 'habit_3', icon: '🎯', title: '习惯入门', desc: '连续完成任意习惯3天', category: 'habit', rarity: 'common',
    condition: function(data) { return data.habitMaxStreak >= 3 },
    progress: function(data) { return Math.min(data.habitMaxStreak, 3) }, maxProgress: 3 },
  { id: 'habit_7', icon: '💪', title: '习惯达人', desc: '连续完成任意习惯7天', category: 'habit', rarity: 'common',
    condition: function(data) { return data.habitMaxStreak >= 7 },
    progress: function(data) { return Math.min(data.habitMaxStreak, 7) }, maxProgress: 7 },
  { id: 'habit_30', icon: '🏅', title: '习惯大师', desc: '连续完成任意习惯30天', category: 'habit', rarity: 'rare',
    condition: function(data) { return data.habitMaxStreak >= 30 },
    progress: function(data) { return Math.min(data.habitMaxStreak, 30) }, maxProgress: 30 },
  { id: 'habit_all_day', icon: '✅', title: '全勤小达人', desc: '一天内完成所有习惯', category: 'habit', rarity: 'rare',
    condition: function(data) { return data.allHabitsDoneToday },
    progress: function(data) { return data.allHabitsDoneToday ? 1 : 0 }, maxProgress: 1 },
  { id: 'habit_100', icon: '💯', title: '百次打卡', desc: '累计打卡100次', category: 'habit', rarity: 'rare',
    condition: function(data) { return data.totalHabitRecords >= 100 },
    progress: function(data) { return Math.min(data.totalHabitRecords, 100) }, maxProgress: 100 },

  // ===== 识字成就 =====
  { id: 'cards_10', icon: '📖', title: '识字入门', desc: '认识10个汉字', category: 'learn', rarity: 'common',
    condition: function(data) { return data.cardsLearned >= 10 },
    progress: function(data) { return Math.min(data.cardsLearned, 10) }, maxProgress: 10 },
  { id: 'cards_50', icon: '📚', title: '识字能手', desc: '认识50个汉字', category: 'learn', rarity: 'common',
    condition: function(data) { return data.cardsLearned >= 50 },
    progress: function(data) { return Math.min(data.cardsLearned, 50) }, maxProgress: 50 },
  { id: 'cards_100', icon: '🎓', title: '识字大师', desc: '认识100个汉字', category: 'learn', rarity: 'rare',
    condition: function(data) { return data.cardsLearned >= 100 },
    progress: function(data) { return Math.min(data.cardsLearned, 100) }, maxProgress: 100 },
  { id: 'cards_all_120', icon: '👑', title: '汉字全通', desc: '学完全部120个汉字', category: 'learn', rarity: 'legendary',
    condition: function(data) { return data.cardsLearned >= 120 },
    progress: function(data) { return Math.min(data.cardsLearned, 120) }, maxProgress: 120 },

  // ===== 古诗成就 =====
  { id: 'poems_5', icon: '📜', title: '诗歌入门', desc: '背诵5首古诗', category: 'learn', rarity: 'common',
    condition: function(data) { return data.poemsMemorized >= 5 },
    progress: function(data) { return Math.min(data.poemsMemorized, 5) }, maxProgress: 5 },
  { id: 'poems_10', icon: '🎭', title: '诗歌达人', desc: '背诵10首古诗', category: 'learn', rarity: 'common',
    condition: function(data) { return data.poemsMemorized >= 10 },
    progress: function(data) { return Math.min(data.poemsMemorized, 10) }, maxProgress: 10 },
  { id: 'poems_25', icon: '🏅', title: '诗歌大师', desc: '背诵全部25首古诗', category: 'learn', rarity: 'legendary',
    condition: function(data) { return data.poemsMemorized >= 25 },
    progress: function(data) { return Math.min(data.poemsMemorized, 25) }, maxProgress: 25 },

  // ===== 数字学习成就 =====
  { id: 'numbers_10', icon: '🔢', title: '数字入门', desc: '学习10个数字', category: 'learn', rarity: 'common',
    condition: function(data) { return data.numbersLearned >= 10 },
    progress: function(data) { return Math.min(data.numbersLearned, 10) }, maxProgress: 10 },
  { id: 'numbers_50', icon: '🔟', title: '数字能手', desc: '学习50个数字', category: 'learn', rarity: 'common',
    condition: function(data) { return data.numbersLearned >= 50 },
    progress: function(data) { return Math.min(data.numbersLearned, 50) }, maxProgress: 50 },
  { id: 'numbers_100', icon: '💯', title: '数字大师', desc: '学完全部100个数字', category: 'learn', rarity: 'rare',
    condition: function(data) { return data.numbersLearned >= 100 },
    progress: function(data) { return Math.min(data.numbersLearned, 100) }, maxProgress: 100 },

  // ===== 英语学习成就 =====
  { id: 'english_10', icon: '🔤', title: '英语入门', desc: '学习10个英语单词', category: 'learn', rarity: 'common',
    condition: function(data) { return data.englishLearned >= 10 },
    progress: function(data) { return Math.min(data.englishLearned, 10) }, maxProgress: 10 },
  { id: 'english_30', icon: '📝', title: '英语能手', desc: '学习30个英语单词', category: 'learn', rarity: 'common',
    condition: function(data) { return data.englishLearned >= 30 },
    progress: function(data) { return Math.min(data.englishLearned, 30) }, maxProgress: 30 },
  { id: 'english_56', icon: '🌍', title: '英语大师', desc: '学完全部56个英语单词', category: 'learn', rarity: 'rare',
    condition: function(data) { return data.englishLearned >= 56 },
    progress: function(data) { return Math.min(data.englishLearned, 56) }, maxProgress: 56 },

  // ===== 学习综合成就 =====
  { id: 'learn_all', icon: '🌟', title: '学习全能', desc: '四个学习模块各学过至少1个', category: 'learn', rarity: 'rare',
    condition: function(data) { return data.cardsLearned >= 1 && data.poemsMemorized >= 1 && data.numbersLearned >= 1 && data.englishLearned >= 1 },
    progress: function(data) { return (data.cardsLearned >= 1 ? 1 : 0) + (data.poemsMemorized >= 1 ? 1 : 0) + (data.numbersLearned >= 1 ? 1 : 0) + (data.englishLearned >= 1 ? 1 : 0) }, maxProgress: 4 },

  // ===== 画画成就 =====
  { id: 'draw_1', icon: '🎨', title: '第一幅画', desc: '画第一幅画', category: 'special', rarity: 'common',
    condition: function(data) { return data.drawingsCount >= 1 },
    progress: function(data) { return Math.min(data.drawingsCount, 1) }, maxProgress: 1 },
  { id: 'draw_5', icon: '🖌️', title: '绘画入门', desc: '画5幅画', category: 'special', rarity: 'common',
    condition: function(data) { return data.drawingsCount >= 5 },
    progress: function(data) { return Math.min(data.drawingsCount, 5) }, maxProgress: 5 },
  { id: 'draw_20', icon: '🖼️', title: '绘画达人', desc: '画20幅画', category: 'special', rarity: 'rare',
    condition: function(data) { return data.drawingsCount >= 20 },
    progress: function(data) { return Math.min(data.drawingsCount, 20) }, maxProgress: 20 },
  { id: 'draw_50', icon: '🏆', title: '绘画大师', desc: '画50幅画', category: 'special', rarity: 'legendary',
    condition: function(data) { return data.drawingsCount >= 50 },
    progress: function(data) { return Math.min(data.drawingsCount, 50) }, maxProgress: 50 },

  // ===== 笔记成就 =====
  { id: 'notes_1', icon: '✏️', title: '第一篇笔记', desc: '写第一篇笔记', category: 'special', rarity: 'common',
    condition: function(data) { return data.notesCount >= 1 },
    progress: function(data) { return Math.min(data.notesCount, 1) }, maxProgress: 1 },
  { id: 'notes_3', icon: '📝', title: '笔记入门', desc: '写3篇笔记', category: 'special', rarity: 'common',
    condition: function(data) { return data.notesCount >= 3 },
    progress: function(data) { return Math.min(data.notesCount, 3) }, maxProgress: 3 },
  { id: 'notes_10', icon: '📓', title: '笔记达人', desc: '写10篇笔记', category: 'special', rarity: 'common',
    condition: function(data) { return data.notesCount >= 10 },
    progress: function(data) { return Math.min(data.notesCount, 10) }, maxProgress: 10 },
  { id: 'notes_30', icon: '📖', title: '笔记大师', desc: '写30篇笔记', category: 'special', rarity: 'rare',
    condition: function(data) { return data.notesCount >= 30 },
    progress: function(data) { return Math.min(data.notesCount, 30) }, maxProgress: 30 },

  // ===== 故事冒险成就 =====
  { id: 'story_ch1', icon: '⚔️', title: '初出茅庐', desc: '完成第1章故事', category: 'story', rarity: 'common',
    condition: function(data) { return data.storyChapter >= 2 || data.storyRound >= 2 },
    progress: function(data) { return (data.storyChapter >= 2 || data.storyRound >= 2) ? 1 : 0 }, maxProgress: 1 },
  { id: 'story_round2', icon: '🔄', title: '二周目', desc: '进入第2轮冒险', category: 'story', rarity: 'rare',
    condition: function(data) { return data.storyRound >= 2 },
    progress: function(data) { return data.storyRound >= 2 ? 1 : 0 }, maxProgress: 1 },
  { id: 'story_10_enemies', icon: '🐉', title: '怪物猎人', desc: '累计击败10个敌人', category: 'story', rarity: 'rare',
    condition: function(data) { return data.totalEnemiesDefeated >= 10 },
    progress: function(data) { return Math.min(data.totalEnemiesDefeated, 10) }, maxProgress: 10 },
  { id: 'story_3_rounds', icon: '🏰', title: '冒险老手', desc: '完成3轮冒险', category: 'story', rarity: 'legendary',
    condition: function(data) { return data.storyRound >= 3 },
    progress: function(data) { return Math.min(data.storyRound, 3) }, maxProgress: 3 },

  // ===== 摆摊成就 =====
  { id: 'stall_1', icon: '🏪', title: '小老板', desc: '完成第一笔销售', category: 'special', rarity: 'common',
    condition: function(data) { return data.stallSalesCount >= 1 },
    progress: function(data) { return Math.min(data.stallSalesCount, 1) }, maxProgress: 1 },
  { id: 'stall_10', icon: '💰', title: '赚钱能手', desc: '累计完成10笔销售', category: 'special', rarity: 'common',
    condition: function(data) { return data.stallSalesCount >= 10 },
    progress: function(data) { return Math.min(data.stallSalesCount, 10) }, maxProgress: 10 },
  { id: 'stall_50', icon: '🏆', title: '销售冠军', desc: '累计完成50笔销售', category: 'special', rarity: 'rare',
    condition: function(data) { return data.stallSalesCount >= 50 },
    progress: function(data) { return Math.min(data.stallSalesCount, 50) }, maxProgress: 50 },
  { id: 'stall_100', icon: '👑', title: '商业大亨', desc: '累计完成100笔销售', category: 'special', rarity: 'legendary',
    condition: function(data) { return data.stallSalesCount >= 100 },
    progress: function(data) { return Math.min(data.stallSalesCount, 100) }, maxProgress: 100 },
  { id: 'stall_revenue_50', icon: '💵', title: '第一桶金', desc: '累计销售额达到50元', category: 'special', rarity: 'common',
    condition: function(data) { return data.stallTotalRevenue >= 50 },
    progress: function(data) { return Math.min(data.stallTotalRevenue, 50) }, maxProgress: 50 },
  { id: 'stall_revenue_200', icon: '💎', title: '小富翁', desc: '累计销售额达到200元', category: 'special', rarity: 'rare',
    condition: function(data) { return data.stallTotalRevenue >= 200 },
    progress: function(data) { return Math.min(data.stallTotalRevenue, 200) }, maxProgress: 200 },
  { id: 'stall_profit', icon: '📈', title: '理财小能手', desc: '累计盈利达到50元', category: 'special', rarity: 'rare',
    condition: function(data) { return data.stallTotalProfit >= 50 },
    progress: function(data) { return Math.min(data.stallTotalProfit, 50) }, maxProgress: 50 },
  { id: 'stall_products_5', icon: '📦', title: '货如轮转', desc: '拥有5种不同商品', category: 'special', rarity: 'common',
    condition: function(data) { return data.stallProductTypes >= 5 },
    progress: function(data) { return Math.min(data.stallProductTypes, 5) }, maxProgress: 5 },

  // ===== 猜拳游戏成就 =====
  { id: 'rps_first_win', icon: '🥊', title: '初战告捷', desc: '猜拳首次获胜', category: 'game', rarity: 'common',
    condition: function(data) { return data.rpsWins >= 1 },
    progress: function(data) { return Math.min(data.rpsWins, 1) }, maxProgress: 1 },
  { id: 'rps_10_wins', icon: '✊', title: '猜拳高手', desc: '猜拳累计获胜10次', category: 'game', rarity: 'common',
    condition: function(data) { return data.rpsWins >= 10 },
    progress: function(data) { return Math.min(data.rpsWins, 10) }, maxProgress: 10 },
  { id: 'rps_50_wins', icon: '🏆', title: '猜拳大师', desc: '猜拳累计获胜50次', category: 'game', rarity: 'rare',
    condition: function(data) { return data.rpsWins >= 50 },
    progress: function(data) { return Math.min(data.rpsWins, 50) }, maxProgress: 50 },
  { id: 'rps_streak_5', icon: '🔥', title: '连胜达人', desc: '猜拳5连胜', category: 'game', rarity: 'rare',
    condition: function(data) { return data.rpsBestStreak >= 5 },
    progress: function(data) { return Math.min(data.rpsBestStreak, 5) }, maxProgress: 5 },
  { id: 'rps_challenge_5', icon: '⚔️', title: '闯关勇士', desc: '闯关挑战达到第5关', category: 'game', rarity: 'common',
    condition: function(data) { return data.rpsChallengeLevel >= 5 },
    progress: function(data) { return Math.min(data.rpsChallengeLevel - 1, 5) }, maxProgress: 5 },
  { id: 'rps_challenge_10', icon: '👑', title: '闯关王者', desc: '通关闯关挑战第10关', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.rpsChallengeLevel >= 11 },
    progress: function(data) { return Math.min(data.rpsChallengeLevel - 1, 10) }, maxProgress: 10 },
  { id: 'rps_story_done', icon: '🐉', title: '故事英雄', desc: '通关故事冒险模式', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.rpsStoryDone },
    progress: function(data) { return data.rpsStoryDone ? 1 : 0 }, maxProgress: 1 },

  // ===== 骰子游戏成就 =====
  { id: 'dice_first_win', icon: '🎲', title: '首掷制胜', desc: '骰子游戏首次获胜', category: 'game', rarity: 'common',
    condition: function(data) { return data.diceWins >= 1 },
    progress: function(data) { return Math.min(data.diceWins, 1) }, maxProgress: 1 },
  { id: 'dice_10_wins', icon: '🎯', title: '骰子高手', desc: '骰子累计获胜10次', category: 'game', rarity: 'common',
    condition: function(data) { return data.diceWins >= 10 },
    progress: function(data) { return Math.min(data.diceWins, 10) }, maxProgress: 10 },
  { id: 'dice_leopard', icon: '🐆', title: '豹子玩家', desc: '摇出1次豹子', category: 'game', rarity: 'rare',
    condition: function(data) { return data.diceLeopardCount >= 1 },
    progress: function(data) { return Math.min(data.diceLeopardCount, 1) }, maxProgress: 1 },
  { id: 'dice_leopard_5', icon: '💎', title: '豹子大师', desc: '摇出5次豹子', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.diceLeopardCount >= 5 },
    progress: function(data) { return Math.min(data.diceLeopardCount, 5) }, maxProgress: 5 },
  { id: 'dice_mission_10', icon: '📋', title: '任务达人', desc: '完成10个任务骰子任务', category: 'game', rarity: 'common',
    condition: function(data) { return data.diceMissionsDone >= 10 },
    progress: function(data) { return Math.min(data.diceMissionsDone, 10) }, maxProgress: 10 },
  { id: 'dice_mission_all', icon: '🌟', title: '任务大师', desc: '完成全部30个任务骰子任务', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.diceMissionsDone >= 30 },
    progress: function(data) { return Math.min(data.diceMissionsDone, 30) }, maxProgress: 30 },
  { id: 'dice_streak_5', icon: '🔥', title: '连胜骰神', desc: '骰子游戏5连胜', category: 'game', rarity: 'rare',
    condition: function(data) { return data.diceBestStreak >= 5 },
    progress: function(data) { return Math.min(data.diceBestStreak, 5) }, maxProgress: 5 },

  // ===== 飞行棋成就 =====
  { id: 'flight_first_win', icon: '✈️', title: '首次飞行', desc: '赢得第一局飞行棋', category: 'game', rarity: 'common',
    condition: function(data) { return data.flightWins >= 1 },
    progress: function(data) { return Math.min(data.flightWins, 1) }, maxProgress: 1 },
  { id: 'flight_10_wins', icon: '🛫', title: '飞行达人', desc: '赢得10局飞行棋', category: 'game', rarity: 'rare',
    condition: function(data) { return data.flightWins >= 10 },
    progress: function(data) { return Math.min(data.flightWins, 10) }, maxProgress: 10 },
  { id: 'flight_perfect', icon: '🏆', title: '完美飞行', desc: '4架飞机全部到达且无人被撞回', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.flightPerfect >= 1 },
    progress: function(data) { return Math.min(data.flightPerfect, 1) }, maxProgress: 1 },
  { id: 'flight_speed', icon: '⚡', title: '闪电飞行', desc: '20回合内完成一局', category: 'game', rarity: 'rare',
    condition: function(data) { return data.flightSpeedWin >= 1 },
    progress: function(data) { return Math.min(data.flightSpeedWin, 1) }, maxProgress: 1 },
  { id: 'flight_item_master', icon: '🎁', title: '道具大师', desc: '一局中使用3个道具', category: 'game', rarity: 'common',
    condition: function(data) { return data.flightItemMaster >= 1 },
    progress: function(data) { return Math.min(data.flightItemMaster, 1) }, maxProgress: 1 },
  { id: 'flight_hard_win', icon: '💎', title: '困难征服者', desc: '在困难模式下获胜', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.flightHardWin >= 1 },
    progress: function(data) { return Math.min(data.flightHardWin, 1) }, maxProgress: 1 },

  // ===== 俄罗斯方块成就 =====
  { id: 'tetris_first_game', icon: '🧱', title: '方块新手', desc: '完成第一局俄罗斯方块', category: 'game', rarity: 'common',
    condition: function(data) { return data.tetrisGames >= 1 },
    progress: function(data) { return Math.min(data.tetrisGames, 1) }, maxProgress: 1 },
  { id: 'tetris_100_lines', icon: '📏', title: '消行达人', desc: '累计消除100行', category: 'game', rarity: 'common',
    condition: function(data) { return data.tetrisTotalLines >= 100 },
    progress: function(data) { return Math.min(data.tetrisTotalLines, 100) }, maxProgress: 100 },
  { id: 'tetris_1000_lines', icon: '🏅', title: '消行大师', desc: '累计消除1000行', category: 'game', rarity: 'rare',
    condition: function(data) { return data.tetrisTotalLines >= 1000 },
    progress: function(data) { return Math.min(data.tetrisTotalLines, 1000) }, maxProgress: 1000 },
  { id: 'tetris_tetris', icon: '💎', title: '完美四消', desc: '一次消除4行（Tetris）', category: 'game', rarity: 'rare',
    condition: function(data) { return data.tetrisTetrisCount >= 1 },
    progress: function(data) { return Math.min(data.tetrisTetrisCount, 1) }, maxProgress: 1 },
  { id: 'tetris_level_5', icon: '⭐', title: '速度挑战者', desc: '达到5级速度', category: 'game', rarity: 'common',
    condition: function(data) { return data.tetrisBestLevel >= 5 },
    progress: function(data) { return Math.min(data.tetrisBestLevel, 5) }, maxProgress: 5 },
  { id: 'tetris_level_10', icon: '🔥', title: '极速王者', desc: '达到满级10级', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.tetrisBestLevel >= 10 },
    progress: function(data) { return Math.min(data.tetrisBestLevel, 10) }, maxProgress: 10 },
  { id: 'tetris_adventure_clear', icon: '⚔️', title: '冒险英雄', desc: '通关冒险模式全部7章', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.tetrisAdventureDone },
    progress: function(data) { return data.tetrisAdventureDone ? 1 : 0 }, maxProgress: 1 },
  { id: 'tetris_puzzle_20', icon: '🧩', title: '拼图大师', desc: '通关全部20个拼图关卡', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.tetrisPuzzleLevels >= 20 },
    progress: function(data) { return Math.min(data.tetrisPuzzleLevels, 20) }, maxProgress: 20 },
  { id: 'tetris_all_stars', icon: '🌟', title: '满星通关', desc: '拼图模式获得全部60颗星', category: 'game', rarity: 'legendary',
    condition: function(data) { return data.tetrisPuzzleStars >= 60 },
    progress: function(data) { return Math.min(data.tetrisPuzzleStars, 60) }, maxProgress: 60 },
  { id: 'tetris_score_10000', icon: '🏆', title: '万分先生', desc: '单局得分超过10000', category: 'game', rarity: 'rare',
    condition: function(data) { return data.tetrisBestScore >= 10000 },
    progress: function(data) { return Math.min(data.tetrisBestScore, 10000) }, maxProgress: 10000 },

  // ===== 游戏综合成就 =====
  { id: 'game_play_30', icon: '🎮', title: '游戏迷', desc: '游戏累计游玩30局', category: 'game', rarity: 'common',
    condition: function(data) { return data.gameTotalPlays >= 30 },
    progress: function(data) { return Math.min(data.gameTotalPlays, 30) }, maxProgress: 30 },
  { id: 'game_play_100', icon: '🎪', title: '游戏狂人', desc: '游戏累计游玩100局', category: 'game', rarity: 'rare',
    condition: function(data) { return data.gameTotalPlays >= 100 },
    progress: function(data) { return Math.min(data.gameTotalPlays, 100) }, maxProgress: 100 },

  // ===== 特殊成就 =====
  { id: 'early_bird', icon: '🐦', title: '早起鸟儿', desc: '早上7点前完成打卡', category: 'special', rarity: 'rare',
    condition: function(data) { return data.hasEarlyBird },
    progress: function(data) { return data.hasEarlyBird ? 1 : 0 }, maxProgress: 1 },
  { id: 'night_owl', icon: '🦉', title: '夜猫子', desc: '晚上9点后完成打卡', category: 'special', rarity: 'common',
    condition: function(data) { return data.hasNightOwl },
    progress: function(data) { return data.hasNightOwl ? 1 : 0 }, maxProgress: 1 },
  { id: 'weekend_warrior', icon: '🎉', title: '周末战士', desc: '周末完成所有习惯', category: 'special', rarity: 'rare',
    condition: function(data) { return data.weekendWarrior },
    progress: function(data) { return data.weekendWarrior ? 1 : 0 }, maxProgress: 1 },

  // ===== 综合成就 =====
  { id: 'all_rounder', icon: '⭐', title: '全面发展', desc: '每个模块都有记录', category: 'special', rarity: 'rare',
    condition: function(data) { return data.brushingStreak >= 1 && data.cardsLearned >= 1 && data.drawingsCount >= 1 && data.notesCount >= 1 },
    progress: function(data) { return (data.brushingStreak >= 1 ? 1 : 0) + (data.cardsLearned >= 1 ? 1 : 0) + (data.drawingsCount >= 1 ? 1 : 0) + (data.notesCount >= 1 ? 1 : 0) }, maxProgress: 4 },
  { id: 'super_star', icon: '🌟', title: '超级之星', desc: '解锁15个成就', category: 'special', rarity: 'rare',
    condition: function(data) { return data.unlockedCount >= 15 },
    progress: function(data) { return Math.min(data.unlockedCount, 15) }, maxProgress: 15 },
  { id: 'legend', icon: '👑', title: '传说之子', desc: '解锁全部成就', category: 'special', rarity: 'legendary',
    condition: function(data) { return data.unlockedCount >= ACHIEVEMENTS.length },
    progress: function(data) { return Math.min(data.unlockedCount, ACHIEVEMENTS.length) }, maxProgress: 80 }
]

module.exports = {
  RARITY: RARITY,
  ACHIEVEMENTS: ACHIEVEMENTS
}
