/**
 * 英语单词 Level 1 - 幼儿园/启蒙
 * 基础词汇：问候、数字、颜色、动物、水果、身体、家人
 */
module.exports = [
  // 问候
  { id: 'e001', word: 'Hello', phonetic: '/həˈloʊ/', meaning: '你好', category: '问候', level: 'L1' },
  { id: 'e002', word: 'Hi', phonetic: '/haɪ/', meaning: '嗨', category: '问候', level: 'L1' },
  { id: 'e003', word: 'Goodbye', phonetic: '/ɡʊdˈbaɪ/', meaning: '再见', category: '问候', level: 'L1' },
  { id: 'e004', word: 'Please', phonetic: '/pliːz/', meaning: '请', category: '问候', level: 'L1' },
  { id: 'e005', word: 'Thank you', phonetic: '/θæŋk juː/', meaning: '谢谢', category: '问候', level: 'L1' },
  { id: 'e006', word: 'Sorry', phonetic: '/ˈsɒri/', meaning: '对不起', category: '问候', level: 'L1' },
  { id: 'e007', word: 'Yes', phonetic: '/jes/', meaning: '是的', category: '问候', level: 'L1' },
  { id: 'e008', word: 'No', phonetic: '/noʊ/', meaning: '不', category: '问候', level: 'L1' },
  { id: 'e009', word: 'OK', phonetic: '/ˌoʊˈkeɪ/', meaning: '好的', category: '问候', level: 'L1' },
  { id: 'e010', word: 'Bye', phonetic: '/baɪ/', meaning: '拜拜', category: '问候', level: 'L1' },

  // 数字
  { id: 'e011', word: 'One', phonetic: '/wʌn/', meaning: '一', category: '数字', level: 'L1' },
  { id: 'e012', word: 'Two', phonetic: '/tuː/', meaning: '二', category: '数字', level: 'L1' },
  { id: 'e013', word: 'Three', phonetic: '/θriː/', meaning: '三', category: '数字', level: 'L1' },
  { id: 'e014', word: 'Four', phonetic: '/fɔːr/', meaning: '四', category: '数字', level: 'L1' },
  { id: 'e015', word: 'Five', phonetic: '/faɪv/', meaning: '五', category: '数字', level: 'L1' },
  { id: 'e016', word: 'Six', phonetic: '/sɪks/', meaning: '六', category: '数字', level: 'L1' },
  { id: 'e017', word: 'Seven', phonetic: '/ˈsevn/', meaning: '七', category: '数字', level: 'L1' },
  { id: 'e018', word: 'Eight', phonetic: '/eɪt/', meaning: '八', category: '数字', level: 'L1' },
  { id: 'e019', word: 'Nine', phonetic: '/naɪn/', meaning: '九', category: '数字', level: 'L1' },
  { id: 'e020', word: 'Ten', phonetic: '/ten/', meaning: '十', category: '数字', level: 'L1' },

  // 颜色
  { id: 'e021', word: 'Red', phonetic: '/red/', meaning: '红色', category: '颜色', level: 'L1' },
  { id: 'e022', word: 'Blue', phonetic: '/bluː/', meaning: '蓝色', category: '颜色', level: 'L1' },
  { id: 'e023', word: 'Green', phonetic: '/ɡriːn/', meaning: '绿色', category: '颜色', level: 'L1' },
  { id: 'e024', word: 'Yellow', phonetic: '/ˈjeloʊ/', meaning: '黄色', category: '颜色', level: 'L1' },
  { id: 'e025', word: 'White', phonetic: '/waɪt/', meaning: '白色', category: '颜色', level: 'L1' },
  { id: 'e026', word: 'Black', phonetic: '/blæk/', meaning: '黑色', category: '颜色', level: 'L1' },
  { id: 'e027', word: 'Pink', phonetic: '/pɪŋk/', meaning: '粉色', category: '颜色', level: 'L1' },
  { id: 'e028', word: 'Orange', phonetic: '/ˈɒrɪndʒ/', meaning: '橙色', category: '颜色', level: 'L1' },
  { id: 'e029', word: 'Purple', phonetic: '/ˈpɜːrpl/', meaning: '紫色', category: '颜色', level: 'L1' },
  { id: 'e030', word: 'Brown', phonetic: '/braʊn/', meaning: '棕色', category: '颜色', level: 'L1' },

  // 动物
  { id: 'e031', word: 'Cat', phonetic: '/kæt/', meaning: '猫', category: '动物', level: 'L1' },
  { id: 'e032', word: 'Dog', phonetic: '/dɒɡ/', meaning: '狗', category: '动物', level: 'L1' },
  { id: 'e033', word: 'Bird', phonetic: '/bɜːrd/', meaning: '鸟', category: '动物', level: 'L1' },
  { id: 'e034', word: 'Fish', phonetic: '/fɪʃ/', meaning: '鱼', category: '动物', level: 'L1' },
  { id: 'e035', word: 'Rabbit', phonetic: '/ˈræbɪt/', meaning: '兔子', category: '动物', level: 'L1' },
  { id: 'e036', word: 'Duck', phonetic: '/dʌk/', meaning: '鸭子', category: '动物', level: 'L1' },
  { id: 'e037', word: 'Pig', phonetic: '/pɪɡ/', meaning: '猪', category: '动物', level: 'L1' },
  { id: 'e038', word: 'Cow', phonetic: '/kaʊ/', meaning: '牛', category: '动物', level: 'L1' },
  { id: 'e039', word: 'Horse', phonetic: '/hɔːrs/', meaning: '马', category: '动物', level: 'L1' },
  { id: 'e040', word: 'Bear', phonetic: '/ber/', meaning: '熊', category: '动物', level: 'L1' },

  // 水果
  { id: 'e041', word: 'Apple', phonetic: '/ˈæpl/', meaning: '苹果', category: '水果', level: 'L1' },
  { id: 'e042', word: 'Banana', phonetic: '/bəˈnænə/', meaning: '香蕉', category: '水果', level: 'L1' },
  { id: 'e043', word: 'Grape', phonetic: '/ɡreɪp/', meaning: '葡萄', category: '水果', level: 'L1' },
  { id: 'e044', word: 'Watermelon', phonetic: '/ˈwɔːtərmelən/', meaning: '西瓜', category: '水果', level: 'L1' },
  { id: 'e045', word: 'Strawberry', phonetic: '/ˈstrɔːberi/', meaning: '草莓', category: '水果', level: 'L1' },
  { id: 'e046', word: 'Orange', phonetic: '/ˈɒrɪndʒ/', meaning: '橙子', category: '水果', level: 'L1' },
  { id: 'e047', word: 'Peach', phonetic: '/piːtʃ/', meaning: '桃子', category: '水果', level: 'L1' },
  { id: 'e048', word: 'Pear', phonetic: '/per/', meaning: '梨', category: '水果', level: 'L1' },
  { id: 'e049', word: 'Mango', phonetic: '/ˈmæŋɡoʊ/', meaning: '芒果', category: '水果', level: 'L1' },
  { id: 'e050', word: 'Cherry', phonetic: '/ˈtʃeri/', meaning: '樱桃', category: '水果', level: 'L1' },

  // 身体
  { id: 'e051', word: 'Head', phonetic: '/hed/', meaning: '头', category: '身体', level: 'L1' },
  { id: 'e052', word: 'Eye', phonetic: '/aɪ/', meaning: '眼睛', category: '身体', level: 'L1' },
  { id: 'e053', word: 'Nose', phonetic: '/noʊz/', meaning: '鼻子', category: '身体', level: 'L1' },
  { id: 'e054', word: 'Mouth', phonetic: '/maʊθ/', meaning: '嘴巴', category: '身体', level: 'L1' },
  { id: 'e055', word: 'Ear', phonetic: '/ɪr/', meaning: '耳朵', category: '身体', level: 'L1' },
  { id: 'e056', word: 'Hand', phonetic: '/hænd/', meaning: '手', category: '身体', level: 'L1' },
  { id: 'e057', word: 'Foot', phonetic: '/fʊt/', meaning: '脚', category: '身体', level: 'L1' },
  { id: 'e058', word: 'Arm', phonetic: '/ɑːrm/', meaning: '手臂', category: '身体', level: 'L1' },
  { id: 'e059', word: 'Leg', phonetic: '/leɡ/', meaning: '腿', category: '身体', level: 'L1' },
  { id: 'e060', word: 'Face', phonetic: '/feɪs/', meaning: '脸', category: '身体', level: 'L1' },

  // 家人
  { id: 'e061', word: 'Mother', phonetic: '/ˈmʌðər/', meaning: '妈妈', category: '家人', level: 'L1' },
  { id: 'e062', word: 'Father', phonetic: '/ˈfɑːðər/', meaning: '爸爸', category: '家人', level: 'L1' },
  { id: 'e063', word: 'Sister', phonetic: '/ˈsɪstər/', meaning: '姐妹', category: '家人', level: 'L1' },
  { id: 'e064', word: 'Brother', phonetic: '/ˈbrʌðər/', meaning: '兄弟', category: '家人', level: 'L1' },
  { id: 'e065', word: 'Grandma', phonetic: '/ˈɡrænmɑː/', meaning: '奶奶/外婆', category: '家人', level: 'L1' },
  { id: 'e066', word: 'Grandpa', phonetic: '/ˈɡrænpɑː/', meaning: '爷爷/外公', category: '家人', level: 'L1' },
  { id: 'e067', word: 'Baby', phonetic: '/ˈbeɪbi/', meaning: '宝宝', category: '家人', level: 'L1' },
  { id: 'e068', word: 'Family', phonetic: '/ˈfæməli/', meaning: '家庭', category: '家人', level: 'L1' },

  // 自然
  { id: 'e069', word: 'Sun', phonetic: '/sʌn/', meaning: '太阳', category: '自然', level: 'L1' },
  { id: 'e070', word: 'Moon', phonetic: '/muːn/', meaning: '月亮', category: '自然', level: 'L1' },
  { id: 'e071', word: 'Star', phonetic: '/stɑːr/', meaning: '星星', category: '自然', level: 'L1' },
  { id: 'e072', word: 'Tree', phonetic: '/triː/', meaning: '树', category: '自然', level: 'L1' },
  { id: 'e073', word: 'Flower', phonetic: '/ˈflaʊər/', meaning: '花', category: '自然', level: 'L1' },
  { id: 'e074', word: 'Grass', phonetic: '/ɡræs/', meaning: '草', category: '自然', level: 'L1' },
  { id: 'e075', word: 'Sky', phonetic: '/skaɪ/', meaning: '天空', category: '自然', level: 'L1' },
  { id: 'e076', word: 'Rain', phonetic: '/reɪn/', meaning: '雨', category: '自然', level: 'L1' },
  { id: 'e077', word: 'Snow', phonetic: '/snoʊ/', meaning: '雪', category: '自然', level: 'L1' },
  { id: 'e078', word: 'Wind', phonetic: '/wɪnd/', meaning: '风', category: '自然', level: 'L1' },
  { id: 'e079', word: 'Cloud', phonetic: '/klaʊd/', meaning: '云', category: '自然', level: 'L1' },
  { id: 'e080', word: 'River', phonetic: '/ˈrɪvər/', meaning: '河', category: '自然', level: 'L1' },
  { id: 'e081', word: 'Mountain', phonetic: '/ˈmaʊntən/', meaning: '山', category: '自然', level: 'L1' },

  // 物品
  { id: 'e082', word: 'Book', phonetic: '/bʊk/', meaning: '书', category: '物品', level: 'L1' },
  { id: 'e083', word: 'Ball', phonetic: '/bɔːl/', meaning: '球', category: '物品', level: 'L1' },
  { id: 'e084', word: 'Kite', phonetic: '/kaɪt/', meaning: '风筝', category: '物品', level: 'L1' },
  { id: 'e085', word: 'Toy', phonetic: '/tɔɪ/', meaning: '玩具', category: '物品', level: 'L1' },
  { id: 'e086', word: 'Car', phonetic: '/kɑːr/', meaning: '汽车', category: '物品', level: 'L1' },
  { id: 'e087', word: 'Bus', phonetic: '/bʌs/', meaning: '公交车', category: '物品', level: 'L1' },
  { id: 'e088', word: 'Bike', phonetic: '/baɪk/', meaning: '自行车', category: '物品', level: 'L1' },
  { id: 'e089', word: 'Bed', phonetic: '/bed/', meaning: '床', category: '物品', level: 'L1' },
  { id: 'e090', word: 'Door', phonetic: '/dɔːr/', meaning: '门', category: '物品', level: 'L1' },
  { id: 'e091', word: 'Table', phonetic: '/ˈteɪbl/', meaning: '桌子', category: '物品', level: 'L1' },
  { id: 'e092', word: 'Chair', phonetic: '/tʃer/', meaning: '椅子', category: '物品', level: 'L1' },

  // 食物
  { id: 'e093', word: 'Cake', phonetic: '/keɪk/', meaning: '蛋糕', category: '食物', level: 'L1' },
  { id: 'e094', word: 'Milk', phonetic: '/mɪlk/', meaning: '牛奶', category: '食物', level: 'L1' },
  { id: 'e095', word: 'Egg', phonetic: '/eɡ/', meaning: '鸡蛋', category: '食物', level: 'L1' },
  { id: 'e096', word: 'Rice', phonetic: '/raɪs/', meaning: '米饭', category: '食物', level: 'L1' },
  { id: 'e097', word: 'Bread', phonetic: '/bred/', meaning: '面包', category: '食物', level: 'L1' },
  { id: 'e098', word: 'Water', phonetic: '/ˈwɔːtər/', meaning: '水', category: '食物', level: 'L1' },
  { id: 'e099', word: 'Juice', phonetic: '/dʒuːs/', meaning: '果汁', category: '食物', level: 'L1' },
  { id: 'e100', word: 'Candy', phonetic: '/ˈkændi/', meaning: '糖果', category: '食物', level: 'L1' },

  // 动作
  { id: 'e101', word: 'Eat', phonetic: '/iːt/', meaning: '吃', category: '动作', level: 'L1' },
  { id: 'e102', word: 'Drink', phonetic: '/drɪŋk/', meaning: '喝', category: '动作', level: 'L1' },
  { id: 'e103', word: 'Run', phonetic: '/rʌn/', meaning: '跑', category: '动作', level: 'L1' },
  { id: 'e104', word: 'Walk', phonetic: '/wɔːk/', meaning: '走', category: '动作', level: 'L1' },
  { id: 'e105', word: 'Jump', phonetic: '/dʒʌmp/', meaning: '跳', category: '动作', level: 'L1' },
  { id: 'e106', word: 'Sit', phonetic: '/sɪt/', meaning: '坐', category: '动作', level: 'L1' },
  { id: 'e107', word: 'Stand', phonetic: '/stænd/', meaning: '站', category: '动作', level: 'L1' },
  { id: 'e108', word: 'Sleep', phonetic: '/sliːp/', meaning: '睡觉', category: '动作', level: 'L1' },
  { id: 'e109', word: 'Sing', phonetic: '/sɪŋ/', meaning: '唱歌', category: '动作', level: 'L1' },
  { id: 'e110', word: 'Dance', phonetic: '/dæns/', meaning: '跳舞', category: '动作', level: 'L1' },
  { id: 'e111', word: 'Play', phonetic: '/pleɪ/', meaning: '玩', category: '动作', level: 'L1' },
  { id: 'e112', word: 'Look', phonetic: '/lʊk/', meaning: '看', category: '动作', level: 'L1' },
  { id: 'e113', word: 'Listen', phonetic: '/ˈlɪsn/', meaning: '听', category: '动作', level: 'L1' },
  { id: 'e114', word: 'Give', phonetic: '/ɡɪv/', meaning: '给', category: '动作', level: 'L1' },
  { id: 'e115', word: 'Take', phonetic: '/teɪk/', meaning: '拿', category: '动作', level: 'L1' },

  // 形容词
  { id: 'e116', word: 'Big', phonetic: '/bɪɡ/', meaning: '大的', category: '形容', level: 'L1' },
  { id: 'e117', word: 'Small', phonetic: '/smɔːl/', meaning: '小的', category: '形容', level: 'L1' },
  { id: 'e118', word: 'Good', phonetic: '/ɡʊd/', meaning: '好的', category: '形容', level: 'L1' },
  { id: 'e119', word: 'Bad', phonetic: '/bæd/', meaning: '坏的', category: '形容', level: 'L1' },
  { id: 'e120', word: 'Happy', phonetic: '/ˈhæpi/', meaning: '快乐的', category: '形容', level: 'L1' },
  { id: 'e121', word: 'Sad', phonetic: '/sæd/', meaning: '伤心的', category: '形容', level: 'L1' },
  { id: 'e122', word: 'Hot', phonetic: '/hɒt/', meaning: '热的', category: '形容', level: 'L1' },
  { id: 'e123', word: 'Cold', phonetic: '/koʊld/', meaning: '冷的', category: '形容', level: 'L1' },
  { id: 'e124', word: 'Fast', phonetic: '/fæst/', meaning: '快的', category: '形容', level: 'L1' },
  { id: 'e125', word: 'Slow', phonetic: '/sloʊ/', meaning: '慢的', category: '形容', level: 'L1' },
  { id: 'e126', word: 'New', phonetic: '/nuː/', meaning: '新的', category: '形容', level: 'L1' },
  { id: 'e127', word: 'Old', phonetic: '/oʊld/', meaning: '旧的/老的', category: '形容', level: 'L1' },
  { id: 'e128', word: 'Long', phonetic: '/lɒŋ/', meaning: '长的', category: '形容', level: 'L1' },
  { id: 'e129', word: 'Short', phonetic: '/ʃɔːrt/', meaning: '短的/矮的', category: '形容', level: 'L1' },
  { id: 'e130', word: 'Tall', phonetic: '/tɔːl/', meaning: '高的', category: '形容', level: 'L1' },

  // 学校
  { id: 'e131', word: 'School', phonetic: '/skuːl/', meaning: '学校', category: '学校', level: 'L1' },
  { id: 'e132', word: 'Teacher', phonetic: '/ˈtiːtʃər/', meaning: '老师', category: '学校', level: 'L1' },
  { id: 'e133', word: 'Student', phonetic: '/ˈstuːdnt/', meaning: '学生', category: '学校', level: 'L1' },
  { id: 'e134', word: 'Pen', phonetic: '/pen/', meaning: '笔', category: '学校', level: 'L1' },
  { id: 'e135', word: 'Pencil', phonetic: '/ˈpensl/', meaning: '铅笔', category: '学校', level: 'L1' },
  { id: 'e136', word: 'Bag', phonetic: '/bæɡ/', meaning: '书包', category: '学校', level: 'L1' },

  // 其他常用
  { id: 'e137', word: 'Boy', phonetic: '/bɔɪ/', meaning: '男孩', category: '人物', level: 'L1' },
  { id: 'e138', word: 'Girl', phonetic: '/ɡɜːrl/', meaning: '女孩', category: '人物', level: 'L1' },
  { id: 'e139', word: 'Man', phonetic: '/mæn/', meaning: '男人', category: '人物', level: 'L1' },
  { id: 'e140', word: 'Woman', phonetic: '/ˈwʊmən/', meaning: '女人', category: '人物', level: 'L1' },
  { id: 'e141', word: 'Child', phonetic: '/tʃaɪld/', meaning: '孩子', category: '人物', level: 'L1' },
  { id: 'e142', word: 'Friend', phonetic: '/frend/', meaning: '朋友', category: '人物', level: 'L1' },
  { id: 'e143', word: 'Name', phonetic: '/neɪm/', meaning: '名字', category: '抽象', level: 'L1' },
  { id: 'e144', word: 'Age', phonetic: '/eɪdʒ/', meaning: '年龄', category: '抽象', level: 'L1' },
  { id: 'e145', word: 'Home', phonetic: '/hoʊm/', meaning: '家', category: '地点', level: 'L1' },
  { id: 'e146', word: 'Room', phonetic: '/ruːm/', meaning: '房间', category: '地点', level: 'L1' },
  { id: 'e147', word: 'Door', phonetic: '/dɔːr/', meaning: '门', category: '物品', level: 'L1' },
  { id: 'e148', word: 'Window', phonetic: '/ˈwɪndoʊ/', meaning: '窗户', category: '物品', level: 'L1' },
  { id: 'e149', word: 'Hand', phonetic: '/hænd/', meaning: '手', category: '身体', level: 'L1' },
  { id: 'e150', word: 'Foot', phonetic: '/fʊt/', meaning: '脚', category: '身体', level: 'L1' }
]
