/**
 * 英语单词 Level 2 - 小学低年级 (3-4年级)
 * 词汇：食物、衣物、动作、方位、学校、家居
 */
module.exports = [
  // 食物
  { id: 'e081', word: 'Rice', phonetic: '/raɪs/', meaning: '米饭', category: '食物', level: 'L2' },
  { id: 'e082', word: 'Noodle', phonetic: '/ˈnuːdl/', meaning: '面条', category: '食物', level: 'L2' },
  { id: 'e083', word: 'Bread', phonetic: '/bred/', meaning: '面包', category: '食物', level: 'L2' },
  { id: 'e084', word: 'Meat', phonetic: '/miːt/', meaning: '肉', category: '食物', level: 'L2' },
  { id: 'e085', word: 'Vegetable', phonetic: '/ˈvedʒtəbl/', meaning: '蔬菜', category: '食物', level: 'L2' },
  { id: 'e086', word: 'Soup', phonetic: '/suːp/', meaning: '汤', category: '食物', level: 'L2' },
  { id: 'e087', word: 'Juice', phonetic: '/dʒuːs/', meaning: '果汁', category: '食物', level: 'L2' },
  { id: 'e088', word: 'Candy', phonetic: '/ˈkændi/', meaning: '糖果', category: '食物', level: 'L2' },
  { id: 'e089', word: 'Ice cream', phonetic: '/aɪs kriːm/', meaning: '冰淇淋', category: '食物', level: 'L2' },
  { id: 'e090', word: 'Cookie', phonetic: '/ˈkʊki/', meaning: '饼干', category: '食物', level: 'L2' },

  // 衣物
  { id: 'e091', word: 'Shirt', phonetic: '/ʃɜːrt/', meaning: '衬衫', category: '衣物', level: 'L2' },
  { id: 'e092', word: 'Pants', phonetic: '/pænts/', meaning: '裤子', category: '衣物', level: 'L2' },
  { id: 'e093', word: 'Dress', phonetic: '/dres/', meaning: '裙子', category: '衣物', level: 'L2' },
  { id: 'e094', word: 'Shoes', phonetic: '/ʃuːz/', meaning: '鞋子', category: '衣物', level: 'L2' },
  { id: 'e095', word: 'Hat', phonetic: '/hæt/', meaning: '帽子', category: '衣物', level: 'L2' },
  { id: 'e096', word: 'Coat', phonetic: '/koʊt/', meaning: '外套', category: '衣物', level: 'L2' },
  { id: 'e097', word: 'Socks', phonetic: '/sɒks/', meaning: '袜子', category: '衣物', level: 'L2' },
  { id: 'e098', word: 'Jacket', phonetic: '/ˈdʒækɪt/', meaning: '夹克', category: '衣物', level: 'L2' },
  { id: 'e099', word: 'Skirt', phonetic: '/skɜːrt/', meaning: '短裙', category: '衣物', level: 'L2' },
  { id: 'e100', word: 'Sweater', phonetic: '/ˈswetər/', meaning: '毛衣', category: '衣物', level: 'L2' },

  // 动作
  { id: 'e101', word: 'Run', phonetic: '/rʌn/', meaning: '跑', category: '动作', level: 'L2' },
  { id: 'e102', word: 'Walk', phonetic: '/wɔːk/', meaning: '走', category: '动作', level: 'L2' },
  { id: 'e103', word: 'Jump', phonetic: '/dʒʌmp/', meaning: '跳', category: '动作', level: 'L2' },
  { id: 'e104', word: 'Swim', phonetic: '/swɪm/', meaning: '游泳', category: '动作', level: 'L2' },
  { id: 'e105', word: 'Fly', phonetic: '/flaɪ/', meaning: '飞', category: '动作', level: 'L2' },
  { id: 'e106', word: 'Eat', phonetic: '/iːt/', meaning: '吃', category: '动作', level: 'L2' },
  { id: 'e107', word: 'Drink', phonetic: '/drɪŋk/', meaning: '喝', category: '动作', level: 'L2' },
  { id: 'e108', word: 'Sleep', phonetic: '/sliːp/', meaning: '睡觉', category: '动作', level: 'L2' },
  { id: 'e109', word: 'Read', phonetic: '/riːd/', meaning: '读', category: '动作', level: 'L2' },
  { id: 'e110', word: 'Write', phonetic: '/raɪt/', meaning: '写', category: '动作', level: 'L2' },
  { id: 'e111', word: 'Sing', phonetic: '/sɪŋ/', meaning: '唱歌', category: '动作', level: 'L2' },
  { id: 'e112', word: 'Dance', phonetic: '/dæns/', meaning: '跳舞', category: '动作', level: 'L2' },
  { id: 'e113', word: 'Draw', phonetic: '/drɔː/', meaning: '画画', category: '动作', level: 'L2' },
  { id: 'e114', word: 'Play', phonetic: '/pleɪ/', meaning: '玩', category: '动作', level: 'L2' },
  { id: 'e115', word: 'Sit', phonetic: '/sɪt/', meaning: '坐', category: '动作', level: 'L2' },
  { id: 'e116', word: 'Stand', phonetic: '/stænd/', meaning: '站', category: '动作', level: 'L2' },
  { id: 'e117', word: 'Open', phonetic: '/ˈoʊpən/', meaning: '打开', category: '动作', level: 'L2' },
  { id: 'e118', word: 'Close', phonetic: '/kloʊz/', meaning: '关闭', category: '动作', level: 'L2' },
  { id: 'e119', word: 'Look', phonetic: '/lʊk/', meaning: '看', category: '动作', level: 'L2' },
  { id: 'e120', word: 'Listen', phonetic: '/ˈlɪsn/', meaning: '听', category: '动作', level: 'L2' },

  // 方位
  { id: 'e121', word: 'Up', phonetic: '/ʌp/', meaning: '上', category: '方位', level: 'L2' },
  { id: 'e122', word: 'Down', phonetic: '/daʊn/', meaning: '下', category: '方位', level: 'L2' },
  { id: 'e123', word: 'Left', phonetic: '/left/', meaning: '左', category: '方位', level: 'L2' },
  { id: 'e124', word: 'Right', phonetic: '/raɪt/', meaning: '右', category: '方位', level: 'L2' },
  { id: 'e125', word: 'In', phonetic: '/ɪn/', meaning: '里面', category: '方位', level: 'L2' },
  { id: 'e126', word: 'Out', phonetic: '/aʊt/', meaning: '外面', category: '方位', level: 'L2' },
  { id: 'e127', word: 'Here', phonetic: '/hɪr/', meaning: '这里', category: '方位', level: 'L2' },
  { id: 'e128', word: 'There', phonetic: '/ðer/', meaning: '那里', category: '方位', level: 'L2' },

  // 学校
  { id: 'e129', word: 'School', phonetic: '/skuːl/', meaning: '学校', category: '学校', level: 'L2' },
  { id: 'e130', word: 'Teacher', phonetic: '/ˈtiːtʃər/', meaning: '老师', category: '学校', level: 'L2' },
  { id: 'e131', word: 'Student', phonetic: '/ˈstuːdnt/', meaning: '学生', category: '学校', level: 'L2' },
  { id: 'e132', word: 'Class', phonetic: '/klæs/', meaning: '班级/课', category: '学校', level: 'L2' },
  { id: 'e133', word: 'Desk', phonetic: '/desk/', meaning: '书桌', category: '学校', level: 'L2' },
  { id: 'e134', word: 'Chair', phonetic: '/tʃer/', meaning: '椅子', category: '学校', level: 'L2' },
  { id: 'e135', word: 'Pen', phonetic: '/pen/', meaning: '钢笔', category: '学校', level: 'L2' },
  { id: 'e136', word: 'Pencil', phonetic: '/ˈpensl/', meaning: '铅笔', category: '学校', level: 'L2' },
  { id: 'e137', word: 'Paper', phonetic: '/ˈpeɪpər/', meaning: '纸', category: '学校', level: 'L2' },
  { id: 'e138', word: 'Ruler', phonetic: '/ˈruːlər/', meaning: '尺子', category: '学校', level: 'L2' },
  { id: 'e139', word: 'Bag', phonetic: '/bæɡ/', meaning: '书包', category: '学校', level: 'L2' },
  { id: 'e140', word: 'Homework', phonetic: '/ˈhoʊmwɜːrk/', meaning: '作业', category: '学校', level: 'L2' },

  // 家居
  { id: 'e141', word: 'House', phonetic: '/haʊs/', meaning: '房子', category: '家居', level: 'L2' },
  { id: 'e142', word: 'Room', phonetic: '/ruːm/', meaning: '房间', category: '家居', level: 'L2' },
  { id: 'e143', word: 'Door', phonetic: '/dɔːr/', meaning: '门', category: '家居', level: 'L2' },
  { id: 'e144', word: 'Window', phonetic: '/ˈwɪndoʊ/', meaning: '窗户', category: '家居', level: 'L2' },
  { id: 'e145', word: 'Bed', phonetic: '/bed/', meaning: '床', category: '家居', level: 'L2' },
  { id: 'e146', word: 'Table', phonetic: '/ˈteɪbl/', meaning: '桌子', category: '家居', level: 'L2' },
  { id: 'e147', word: 'Light', phonetic: '/laɪt/', meaning: '灯', category: '家居', level: 'L2' },
  { id: 'e148', word: 'Clock', phonetic: '/klɒk/', meaning: '钟', category: '家居', level: 'L2' },
  { id: 'e149', word: 'Phone', phonetic: '/foʊn/', meaning: '电话', category: '家居', level: 'L2' },
  { id: 'e150', word: 'TV', phonetic: '/ˌtiː ˈviː/', meaning: '电视', category: '家居', level: 'L2' },

  // 形容词
  { id: 'e151', word: 'Beautiful', phonetic: '/ˈbjuːtɪfl/', meaning: '美丽的', category: '形容', level: 'L2' },
  { id: 'e152', word: 'Ugly', phonetic: '/ˈʌɡli/', meaning: '丑的', category: '形容', level: 'L2' },
  { id: 'e153', word: 'Clean', phonetic: '/kliːn/', meaning: '干净的', category: '形容', level: 'L2' },
  { id: 'e154', word: 'Dirty', phonetic: '/ˈdɜːrti/', meaning: '脏的', category: '形容', level: 'L2' },
  { id: 'e155', word: 'Quiet', phonetic: '/ˈkwaɪət/', meaning: '安静的', category: '形容', level: 'L2' },
  { id: 'e156', word: 'Loud', phonetic: '/laʊd/', meaning: '大声的', category: '形容', level: 'L2' },
  { id: 'e157', word: 'Easy', phonetic: '/ˈiːzi/', meaning: '容易的', category: '形容', level: 'L2' },
  { id: 'e158', word: 'Hard', phonetic: '/hɑːrd/', meaning: '难的/硬的', category: '形容', level: 'L2' },
  { id: 'e159', word: 'Soft', phonetic: '/sɒft/', meaning: '软的', category: '形容', level: 'L2' },
  { id: 'e160', word: 'Heavy', phonetic: '/ˈhevi/', meaning: '重的', category: '形容', level: 'L2' },
  { id: 'e161', word: 'Light', phonetic: '/laɪt/', meaning: '轻的/亮的', category: '形容', level: 'L2' },
  { id: 'e162', word: 'Dark', phonetic: '/dɑːrk/', meaning: '暗的', category: '形容', level: 'L2' },
  { id: 'e163', word: 'Full', phonetic: '/fʊl/', meaning: '满的', category: '形容', level: 'L2' },
  { id: 'e164', word: 'Empty', phonetic: '/ˈempti/', meaning: '空的', category: '形容', level: 'L2' },
  { id: 'e165', word: 'Rich', phonetic: '/rɪtʃ/', meaning: '富的', category: '形容', level: 'L2' },
  { id: 'e166', word: 'Poor', phonetic: '/pʊr/', meaning: '穷的', category: '形容', level: 'L2' },
  { id: 'e167', word: 'Safe', phonetic: '/seɪf/', meaning: '安全的', category: '形容', level: 'L2' },
  { id: 'e168', word: 'Dangerous', phonetic: '/ˈdeɪndʒərəs/', meaning: '危险的', category: '形容', level: 'L2' },

  // 身体动作
  { id: 'e169', word: 'Touch', phonetic: '/tʌtʃ/', meaning: '触摸', category: '动作', level: 'L2' },
  { id: 'e170', word: 'Push', phonetic: '/pʊʃ/', meaning: '推', category: '动作', level: 'L2' },
  { id: 'e171', word: 'Pull', phonetic: '/pʊl/', meaning: '拉', category: '动作', level: 'L2' },
  { id: 'e172', word: 'Throw', phonetic: '/θroʊ/', meaning: '扔', category: '动作', level: 'L2' },
  { id: 'e173', word: 'Catch', phonetic: '/kætʃ/', meaning: '接住', category: '动作', level: 'L2' },
  { id: 'e174', word: 'Carry', phonetic: '/ˈkæri/', meaning: '搬运', category: '动作', level: 'L2' },
  { id: 'e175', word: 'Hold', phonetic: '/hoʊld/', meaning: '握住', category: '动作', level: 'L2' },
  { id: 'e176', word: 'Cut', phonetic: '/kʌt/', meaning: '切', category: '动作', level: 'L2' },
  { id: 'e177', word: 'Draw', phonetic: '/drɔː/', meaning: '画', category: '动作', level: 'L2' },
  { id: 'e178', word: 'Paint', phonetic: '/peɪnt/', meaning: '涂色', category: '动作', level: 'L2' },
  { id: 'e179', word: 'Build', phonetic: '/bɪld/', meaning: '建造', category: '动作', level: 'L2' },
  { id: 'e180', word: 'Make', phonetic: '/meɪk/', meaning: '制作', category: '动作', level: 'L2' },
  { id: 'e181', word: 'Wash', phonetic: '/wɒʃ/', meaning: '洗', category: '动作', level: 'L2' },
  { id: 'e182', word: 'Clean', phonetic: '/kliːn/', meaning: '打扫', category: '动作', level: 'L2' },
  { id: 'e183', word: 'Cook', phonetic: '/kʊk/', meaning: '烹饪', category: '动作', level: 'L2' },
  { id: 'e184', word: 'Help', phonetic: '/help/', meaning: '帮助', category: '动作', level: 'L2' },
  { id: 'e185', word: 'Share', phonetic: '/ʃer/', meaning: '分享', category: '动作', level: 'L2' },
  { id: 'e186', word: 'Wait', phonetic: '/weɪt/', meaning: '等待', category: '动作', level: 'L2' },
  { id: 'e187', word: 'Stop', phonetic: '/stɒp/', meaning: '停止', category: '动作', level: 'L2' },
  { id: 'e188', word: 'Start', phonetic: '/stɑːrt/', meaning: '开始', category: '动作', level: 'L2' },
  { id: 'e189', word: 'Try', phonetic: '/traɪ/', meaning: '尝试', category: '动作', level: 'L2' },
  { id: 'e190', word: 'Learn', phonetic: '/lɜːrn/', meaning: '学习', category: '动作', level: 'L2' },
  { id: 'e191', word: 'Teach', phonetic: '/tiːtʃ/', meaning: '教', category: '动作', level: 'L2' },
  { id: 'e192', word: 'Ask', phonetic: '/æsk/', meaning: '问', category: '动作', level: 'L2' },
  { id: 'e193', word: 'Answer', phonetic: '/ˈænsər/', meaning: '回答', category: '动作', level: 'L2' },
  { id: 'e194', word: 'Tell', phonetic: '/tel/', meaning: '告诉', category: '动作', level: 'L2' },
  { id: 'e195', word: 'Speak', phonetic: '/spiːk/', meaning: '说话', category: '动作', level: 'L2' },
  { id: 'e196', word: 'Talk', phonetic: '/tɔːk/', meaning: '谈话', category: '动作', level: 'L2' },
  { id: 'e197', word: 'Call', phonetic: '/kɔːl/', meaning: '打电话/叫', category: '动作', level: 'L2' },
  { id: 'e198', word: 'Show', phonetic: '/ʃoʊ/', meaning: '展示', category: '动作', level: 'L2' },
  { id: 'e199', word: 'Find', phonetic: '/faɪnd/', meaning: '找到', category: '动作', level: 'L2' },
  { id: 'e200', word: 'Put', phonetic: '/pʊt/', meaning: '放', category: '动作', level: 'L2' },
  { id: 'e201', word: 'Get', phonetic: '/ɡet/', meaning: '得到', category: '动作', level: 'L2' },
  { id: 'e202', word: 'Come', phonetic: '/kʌm/', meaning: '来', category: '动作', level: 'L2' },
  { id: 'e203', word: 'Go', phonetic: '/ɡoʊ/', meaning: '去', category: '动作', level: 'L2' },
  { id: 'e204', word: 'Bring', phonetic: '/brɪŋ/', meaning: '带来', category: '动作', level: 'L2' },
  { id: 'e205', word: 'Send', phonetic: '/send/', meaning: '发送', category: '动作', level: 'L2' },
  { id: 'e206', word: 'Need', phonetic: '/niːd/', meaning: '需要', category: '动作', level: 'L2' },
  { id: 'e207', word: 'Want', phonetic: '/wɒnt/', meaning: '想要', category: '动作', level: 'L2' },
  { id: 'e208', word: 'Have', phonetic: '/hæv/', meaning: '有', category: '动作', level: 'L2' },
  { id: 'e209', word: 'Like', phonetic: '/laɪk/', meaning: '喜欢', category: '动作', level: 'L2' },
  { id: 'e210', word: 'Love', phonetic: '/lʌv/', meaning: '爱', category: '动作', level: 'L2' },

  // 更多名词
  { id: 'e211', word: 'Animal', phonetic: '/ˈænɪml/', meaning: '动物', category: '名词', level: 'L2' },
  { id: 'e212', word: 'People', phonetic: '/ˈpiːpl/', meaning: '人们', category: '名词', level: 'L2' },
  { id: 'e213', word: 'Thing', phonetic: '/θɪŋ/', meaning: '东西', category: '名词', level: 'L2' },
  { id: 'e214', word: 'Place', phonetic: '/pleɪs/', meaning: '地方', category: '名词', level: 'L2' },
  { id: 'e215', word: 'Way', phonetic: '/weɪ/', meaning: '路/方式', category: '名词', level: 'L2' },
  { id: 'e216', word: 'Day', phonetic: '/deɪ/', meaning: '天', category: '名词', level: 'L2' },
  { id: 'e217', word: 'Night', phonetic: '/naɪt/', meaning: '夜晚', category: '名词', level: 'L2' },
  { id: 'e218', word: 'Morning', phonetic: '/ˈmɔːrnɪŋ/', meaning: '早上', category: '名词', level: 'L2' },
  { id: 'e219', word: 'Afternoon', phonetic: '/ˌæftərˈnuːn/', meaning: '下午', category: '名词', level: 'L2' },
  { id: 'e220', word: 'Evening', phonetic: '/ˈiːvnɪŋ/', meaning: '晚上', category: '名词', level: 'L2' },
  { id: 'e221', word: 'Today', phonetic: '/təˈdeɪ/', meaning: '今天', category: '名词', level: 'L2' },
  { id: 'e222', word: 'Tomorrow', phonetic: '/təˈmɒroʊ/', meaning: '明天', category: '名词', level: 'L2' },
  { id: 'e223', word: 'Yesterday', phonetic: '/ˈjestərdeɪ/', meaning: '昨天', category: '名词', level: 'L2' },
  { id: 'e224', word: 'Week', phonetic: '/wiːk/', meaning: '周', category: '名词', level: 'L2' },
  { id: 'e225', word: 'Month', phonetic: '/mʌnθ/', meaning: '月', category: '名词', level: 'L2' },
  { id: 'e226', word: 'Year', phonetic: '/jɪr/', meaning: '年', category: '名词', level: 'L2' },
  { id: 'e227', word: 'Time', phonetic: '/taɪm/', meaning: '时间', category: '名词', level: 'L2' },
  { id: 'e228', word: 'Number', phonetic: '/ˈnʌmbər/', meaning: '数字', category: '名词', level: 'L2' },
  { id: 'e229', word: 'Color', phonetic: '/ˈkʌlər/', meaning: '颜色', category: '名词', level: 'L2' },
  { id: 'e230', word: 'Shape', phonetic: '/ʃeɪp/', meaning: '形状', category: '名词', level: 'L2' },
  { id: 'e231', word: 'Picture', phonetic: '/ˈpɪktʃər/', meaning: '图画', category: '名词', level: 'L2' },
  { id: 'e232', word: 'Song', phonetic: '/sɒŋ/', meaning: '歌曲', category: '名词', level: 'L2' },
  { id: 'e233', word: 'Story', phonetic: '/ˈstɔːri/', meaning: '故事', category: '名词', level: 'L2' },
  { id: 'e234', word: 'Game', phonetic: '/ɡeɪm/', meaning: '游戏', category: '名词', level: 'L2' },
  { id: 'e235', word: 'Job', phonetic: '/dʒɒb/', meaning: '工作', category: '名词', level: 'L2' },
  { id: 'e236', word: 'Work', phonetic: '/wɜːrk/', meaning: '工作', category: '名词', level: 'L2' },
  { id: 'e237', word: 'Money', phonetic: '/ˈmʌni/', meaning: '钱', category: '名词', level: 'L2' },
  { id: 'e238', word: 'Paper', phonetic: '/ˈpeɪpər/', meaning: '纸', category: '名词', level: 'L2' },
  { id: 'e239', word: 'Letter', phonetic: '/ˈletər/', meaning: '信/字母', category: '名词', level: 'L2' },
  { id: 'e240', word: 'Word', phonetic: '/wɜːrd/', meaning: '单词', category: '名词', level: 'L2' }
]
