/**
 * 英语单词 Level 3 - 小学高年级 (5-6年级)
 * 词汇：情感、时间、天气、职业、交通、节日、自然、日常
 */
module.exports = [
  // 情感
  { id: 'e161', word: 'Love', phonetic: '/lʌv/', meaning: '爱', category: '情感', level: 'L3' },
  { id: 'e162', word: 'Like', phonetic: '/laɪk/', meaning: '喜欢', category: '情感', level: 'L3' },
  { id: 'e163', word: 'Hate', phonetic: '/heɪt/', meaning: '讨厌', category: '情感', level: 'L3' },
  { id: 'e164', word: 'Angry', phonetic: '/ˈæŋɡri/', meaning: '生气的', category: '情感', level: 'L3' },
  { id: 'e165', word: 'Afraid', phonetic: '/əˈfreɪd/', meaning: '害怕的', category: '情感', level: 'L3' },
  { id: 'e166', word: 'Tired', phonetic: '/ˈtaɪərd/', meaning: '累的', category: '情感', level: 'L3' },
  { id: 'e167', word: 'Excited', phonetic: '/ɪkˈsaɪtɪd/', meaning: '兴奋的', category: '情感', level: 'L3' },
  { id: 'e168', word: 'Bored', phonetic: '/bɔːrd/', meaning: '无聊的', category: '情感', level: 'L3' },
  { id: 'e169', word: 'Surprised', phonetic: '/sərˈpraɪzd/', meaning: '惊讶的', category: '情感', level: 'L3' },
  { id: 'e170', word: 'Proud', phonetic: '/praʊd/', meaning: '骄傲的', category: '情感', level: 'L3' },

  // 时间
  { id: 'e171', word: 'Morning', phonetic: '/ˈmɔːrnɪŋ/', meaning: '早上', category: '时间', level: 'L3' },
  { id: 'e172', word: 'Afternoon', phonetic: '/ˌæftərˈnuːn/', meaning: '下午', category: '时间', level: 'L3' },
  { id: 'e173', word: 'Evening', phonetic: '/ˈiːvnɪŋ/', meaning: '晚上', category: '时间', level: 'L3' },
  { id: 'e174', word: 'Night', phonetic: '/naɪt/', meaning: '夜晚', category: '时间', level: 'L3' },
  { id: 'e175', word: 'Today', phonetic: '/təˈdeɪ/', meaning: '今天', category: '时间', level: 'L3' },
  { id: 'e176', word: 'Tomorrow', phonetic: '/təˈmɒroʊ/', meaning: '明天', category: '时间', level: 'L3' },
  { id: 'e177', word: 'Yesterday', phonetic: '/ˈjestərdeɪ/', meaning: '昨天', category: '时间', level: 'L3' },
  { id: 'e178', word: 'Week', phonetic: '/wiːk/', meaning: '周', category: '时间', level: 'L3' },
  { id: 'e179', word: 'Month', phonetic: '/mʌnθ/', meaning: '月', category: '时间', level: 'L3' },
  { id: 'e180', word: 'Year', phonetic: '/jɪr/', meaning: '年', category: '时间', level: 'L3' },

  // 天气
  { id: 'e181', word: 'Sunny', phonetic: '/ˈsʌni/', meaning: '晴朗的', category: '天气', level: 'L3' },
  { id: 'e182', word: 'Rainy', phonetic: '/ˈreɪni/', meaning: '下雨的', category: '天气', level: 'L3' },
  { id: 'e183', word: 'Cloudy', phonetic: '/ˈklaʊdi/', meaning: '多云的', category: '天气', level: 'L3' },
  { id: 'e184', word: 'Windy', phonetic: '/ˈwɪndi/', meaning: '有风的', category: '天气', level: 'L3' },
  { id: 'e185', word: 'Snowy', phonetic: '/ˈsnoʊi/', meaning: '下雪的', category: '天气', level: 'L3' },
  { id: 'e186', word: 'Rain', phonetic: '/reɪn/', meaning: '雨', category: '天气', level: 'L3' },
  { id: 'e187', word: 'Snow', phonetic: '/snoʊ/', meaning: '雪', category: '天气', level: 'L3' },
  { id: 'e188', word: 'Wind', phonetic: '/wɪnd/', meaning: '风', category: '天气', level: 'L3' },
  { id: 'e189', word: 'Cloud', phonetic: '/klaʊd/', meaning: '云', category: '天气', level: 'L3' },
  { id: 'e190', word: 'Weather', phonetic: '/ˈweðər/', meaning: '天气', category: '天气', level: 'L3' },

  // 职业
  { id: 'e191', word: 'Doctor', phonetic: '/ˈdɒktər/', meaning: '医生', category: '职业', level: 'L3' },
  { id: 'e192', word: 'Nurse', phonetic: '/nɜːrs/', meaning: '护士', category: '职业', level: 'L3' },
  { id: 'e193', word: 'Policeman', phonetic: '/pəˈliːsmən/', meaning: '警察', category: '职业', level: 'L3' },
  { id: 'e194', word: 'Fireman', phonetic: '/ˈfaɪərmən/', meaning: '消防员', category: '职业', level: 'L3' },
  { id: 'e195', word: 'Driver', phonetic: '/ˈdraɪvər/', meaning: '司机', category: '职业', level: 'L3' },
  { id: 'e196', word: 'Cook', phonetic: '/kʊk/', meaning: '厨师', category: '职业', level: 'L3' },
  { id: 'e197', word: 'Farmer', phonetic: '/ˈfɑːrmər/', meaning: '农民', category: '职业', level: 'L3' },
  { id: 'e198', word: 'Worker', phonetic: '/ˈwɜːrkər/', meaning: '工人', category: '职业', level: 'L3' },
  { id: 'e199', word: 'Singer', phonetic: '/ˈsɪŋər/', meaning: '歌手', category: '职业', level: 'L3' },
  { id: 'e200', word: 'Player', phonetic: '/ˈpleɪər/', meaning: '运动员', category: '职业', level: 'L3' },

  // 交通
  { id: 'e201', word: 'Car', phonetic: '/kɑːr/', meaning: '汽车', category: '交通', level: 'L3' },
  { id: 'e202', word: 'Bus', phonetic: '/bʌs/', meaning: '公交车', category: '交通', level: 'L3' },
  { id: 'e203', word: 'Train', phonetic: '/treɪn/', meaning: '火车', category: '交通', level: 'L3' },
  { id: 'e204', word: 'Bike', phonetic: '/baɪk/', meaning: '自行车', category: '交通', level: 'L3' },
  { id: 'e205', word: 'Plane', phonetic: '/pleɪn/', meaning: '飞机', category: '交通', level: 'L3' },
  { id: 'e206', word: 'Ship', phonetic: '/ʃɪp/', meaning: '船', category: '交通', level: 'L3' },
  { id: 'e207', word: 'Taxi', phonetic: '/ˈtæksi/', meaning: '出租车', category: '交通', level: 'L3' },
  { id: 'e208', word: 'Subway', phonetic: '/ˈsʌbweɪ/', meaning: '地铁', category: '交通', level: 'L3' },
  { id: 'e209', word: 'Boat', phonetic: '/boʊt/', meaning: '小船', category: '交通', level: 'L3' },
  { id: 'e210', word: 'Ticket', phonetic: '/ˈtɪkɪt/', meaning: '票', category: '交通', level: 'L3' },

  // 节日
  { id: 'e211', word: 'Christmas', phonetic: '/ˈkrɪsməs/', meaning: '圣诞节', category: '节日', level: 'L3' },
  { id: 'e212', word: 'Birthday', phonetic: '/ˈbɜːrθdeɪ/', meaning: '生日', category: '节日', level: 'L3' },
  { id: 'e213', word: 'New Year', phonetic: '/nuː jɪr/', meaning: '新年', category: '节日', level: 'L3' },
  { id: 'e214', word: 'Party', phonetic: '/ˈpɑːrti/', meaning: '派对', category: '节日', level: 'L3' },
  { id: 'e215', word: 'Gift', phonetic: '/ɡɪft/', meaning: '礼物', category: '节日', level: 'L3' },
  { id: 'e216', word: 'Holiday', phonetic: '/ˈhɒlədeɪ/', meaning: '假期', category: '节日', level: 'L3' },
  { id: 'e217', word: 'Festival', phonetic: '/ˈfestɪvl/', meaning: '节日', category: '节日', level: 'L3' },
  { id: 'e218', word: 'Spring', phonetic: '/sprɪŋ/', meaning: '春天', category: '季节', level: 'L3' },
  { id: 'e219', word: 'Summer', phonetic: '/ˈsʌmər/', meaning: '夏天', category: '季节', level: 'L3' },
  { id: 'e220', word: 'Autumn', phonetic: '/ˈɔːtəm/', meaning: '秋天', category: '季节', level: 'L3' },
  { id: 'e221', word: 'Winter', phonetic: '/ˈwɪntər/', meaning: '冬天', category: '季节', level: 'L3' },

  // 自然
  { id: 'e222', word: 'Mountain', phonetic: '/ˈmaʊntən/', meaning: '山', category: '自然', level: 'L3' },
  { id: 'e223', word: 'River', phonetic: '/ˈrɪvər/', meaning: '河', category: '自然', level: 'L3' },
  { id: 'e224', word: 'Lake', phonetic: '/leɪk/', meaning: '湖', category: '自然', level: 'L3' },
  { id: 'e225', word: 'Sea', phonetic: '/siː/', meaning: '海', category: '自然', level: 'L3' },
  { id: 'e226', word: 'Forest', phonetic: '/ˈfɒrɪst/', meaning: '森林', category: '自然', level: 'L3' },
  { id: 'e227', word: 'Island', phonetic: '/ˈaɪlənd/', meaning: '岛', category: '自然', level: 'L3' },
  { id: 'e228', word: 'Sky', phonetic: '/skaɪ/', meaning: '天空', category: '自然', level: 'L3' },
  { id: 'e229', word: 'Earth', phonetic: '/ɜːrθ/', meaning: '地球', category: '自然', level: 'L3' },
  { id: 'e230', word: 'Garden', phonetic: '/ˈɡɑːrdn/', meaning: '花园', category: '自然', level: 'L3' },

  // 日常
  { id: 'e231', word: 'Breakfast', phonetic: '/ˈbrekfəst/', meaning: '早餐', category: '日常', level: 'L3' },
  { id: 'e232', word: 'Lunch', phonetic: '/lʌntʃ/', meaning: '午餐', category: '日常', level: 'L3' },
  { id: 'e233', word: 'Dinner', phonetic: '/ˈdɪnər/', meaning: '晚餐', category: '日常', level: 'L3' },
  { id: 'e234', word: 'Money', phonetic: '/ˈmʌni/', meaning: '钱', category: '日常', level: 'L3' },
  { id: 'e235', word: 'Shop', phonetic: '/ʃɒp/', meaning: '商店', category: '日常', level: 'L3' },
  { id: 'e236', word: 'Market', phonetic: '/ˈmɑːrkɪt/', meaning: '市场', category: '日常', level: 'L3' },
  { id: 'e237', word: 'Park', phonetic: '/pɑːrk/', meaning: '公园', category: '日常', level: 'L3' },
  { id: 'e238', word: 'Zoo', phonetic: '/zuː/', meaning: '动物园', category: '日常', level: 'L3' },
  { id: 'e239', word: 'Hospital', phonetic: '/ˈhɒspɪtl/', meaning: '医院', category: '日常', level: 'L3' },
  { id: 'e240', word: 'Library', phonetic: '/ˈlaɪbreri/', meaning: '图书馆', category: '日常', level: 'L3' },
  { id: 'e241', word: 'Restaurant', phonetic: '/ˈrestrɒnt/', meaning: '餐厅', category: '日常', level: 'L3' },
  { id: 'e242', word: 'Cinema', phonetic: '/ˈsɪnəmə/', meaning: '电影院', category: '日常', level: 'L3' },
  { id: 'e243', word: 'Bank', phonetic: '/bæŋk/', meaning: '银行', category: '日常', level: 'L3' },
  { id: 'e244', word: 'Post office', phonetic: '/poʊst ˈɒfɪs/', meaning: '邮局', category: '日常', level: 'L3' },
  { id: 'e245', word: 'Supermarket', phonetic: '/ˈsuːpərmɑːrkɪt/', meaning: '超市', category: '日常', level: 'L3' },

  // 更多动词
  { id: 'e246', word: 'Believe', phonetic: '/bɪˈliːv/', meaning: '相信', category: '动词', level: 'L3' },
  { id: 'e247', word: 'Remember', phonetic: '/rɪˈmembər/', meaning: '记住', category: '动词', level: 'L3' },
  { id: 'e248', word: 'Forget', phonetic: '/fərˈɡet/', meaning: '忘记', category: '动词', level: 'L3' },
  { id: 'e249', word: 'Understand', phonetic: '/ˌʌndərˈstænd/', meaning: '理解', category: '动词', level: 'L3' },
  { id: 'e250', word: 'Explain', phonetic: '/ɪkˈspleɪn/', meaning: '解释', category: '动词', level: 'L3' },
  { id: 'e251', word: 'Agree', phonetic: '/əˈɡriː/', meaning: '同意', category: '动词', level: 'L3' },
  { id: 'e252', word: 'Disagree', phonetic: '/ˌdɪsəˈɡriː/', meaning: '不同意', category: '动词', level: 'L3' },
  { id: 'e253', word: 'Decide', phonetic: '/dɪˈsaɪd/', meaning: '决定', category: '动词', level: 'L3' },
  { id: 'e254', word: 'Choose', phonetic: '/tʃuːz/', meaning: '选择', category: '动词', level: 'L3' },
  { id: 'e255', word: 'Plan', phonetic: '/plæn/', meaning: '计划', category: '动词', level: 'L3' },
  { id: 'e256', word: 'Prepare', phonetic: '/prɪˈper/', meaning: '准备', category: '动词', level: 'L3' },
  { id: 'e257', word: 'Arrive', phonetic: '/əˈraɪv/', meaning: '到达', category: '动词', level: 'L3' },
  { id: 'e258', word: 'Leave', phonetic: '/liːv/', meaning: '离开', category: '动词', level: 'L3' },
  { id: 'e259', word: 'Return', phonetic: '/rɪˈtɜːrn/', meaning: '返回', category: '动词', level: 'L3' },
  { id: 'e260', word: 'Travel', phonetic: '/ˈtrævl/', meaning: '旅行', category: '动词', level: 'L3' },
  { id: 'e261', word: 'Visit', phonetic: '/ˈvɪzɪt/', meaning: '拜访/参观', category: '动词', level: 'L3' },
  { id: 'e262', word: 'Enjoy', phonetic: '/ɪnˈdʒɔɪ/', meaning: '享受', category: '动词', level: 'L3' },
  { id: 'e263', word: 'Prefer', phonetic: '/prɪˈfɜːr/', meaning: '更喜欢', category: '动词', level: 'L3' },
  { id: 'e264', word: 'Hate', phonetic: '/heɪt/', meaning: '讨厌', category: '动词', level: 'L3' },
  { id: 'e265', word: 'Miss', phonetic: '/mɪs/', meaning: '想念/错过', category: '动词', level: 'L3' },
  { id: 'e266', word: 'Worry', phonetic: '/ˈwʌri/', meaning: '担心', category: '动词', level: 'L3' },
  { id: 'e267', word: 'Care', phonetic: '/ker/', meaning: '关心', category: '动词', level: 'L3' },
  { id: 'e268', word: 'Hope', phonetic: '/hoʊp/', meaning: '希望', category: '动词', level: 'L3' },
  { id: 'e269', word: 'Wish', phonetic: '/wɪʃ/', meaning: '祝愿', category: '动词', level: 'L3' },
  { id: 'e270', word: 'Expect', phonetic: '/ɪkˈspekt/', meaning: '期待', category: '动词', level: 'L3' },
  { id: 'e271', word: 'Promise', phonetic: '/ˈprɒmɪs/', meaning: '承诺', category: '动词', level: 'L3' },
  { id: 'e272', word: 'Allow', phonetic: '/əˈlaʊ/', meaning: '允许', category: '动词', level: 'L3' },
  { id: 'e273', word: 'Refuse', phonetic: '/rɪˈfjuːz/', meaning: '拒绝', category: '动词', level: 'L3' },
  { id: 'e274', word: 'Accept', phonetic: '/əkˈsept/', meaning: '接受', category: '动词', level: 'L3' },
  { id: 'e275', word: 'Offer', phonetic: '/ˈɒfər/', meaning: '提供', category: '动词', level: 'L3' },

  // 更多形容词
  { id: 'e276', word: 'Important', phonetic: '/ɪmˈpɔːrtənt/', meaning: '重要的', category: '形容', level: 'L3' },
  { id: 'e277', word: 'Interesting', phonetic: '/ˈɪntrəstɪŋ/', meaning: '有趣的', category: '形容', level: 'L3' },
  { id: 'e278', word: 'Boring', phonetic: '/ˈbɔːrɪŋ/', meaning: '无聊的', category: '形容', level: 'L3' },
  { id: 'e279', word: 'Difficult', phonetic: '/ˈdɪfɪkəlt/', meaning: '困难的', category: '形容', level: 'L3' },
  { id: 'e280', word: 'Possible', phonetic: '/ˈpɒsəbl/', meaning: '可能的', category: '形容', level: 'L3' },
  { id: 'e281', word: 'Impossible', phonetic: '/ɪmˈpɒsəbl/', meaning: '不可能的', category: '形容', level: 'L3' },
  { id: 'e282', word: 'Necessary', phonetic: '/ˈnesəseri/', meaning: '必要的', category: '形容', level: 'L3' },
  { id: 'e283', word: 'Different', phonetic: '/ˈdɪfrənt/', meaning: '不同的', category: '形容', level: 'L3' },
  { id: 'e284', word: 'Same', phonetic: '/seɪm/', meaning: '相同的', category: '形容', level: 'L3' },
  { id: 'e285', word: 'Similar', phonetic: '/ˈsɪmələr/', meaning: '相似的', category: '形容', level: 'L3' },
  { id: 'e286', word: 'Special', phonetic: '/ˈspeʃl/', meaning: '特别的', category: '形容', level: 'L3' },
  { id: 'e287', word: 'Popular', phonetic: '/ˈpɒpjələr/', meaning: '受欢迎的', category: '形容', level: 'L3' },
  { id: 'e288', word: 'Famous', phonetic: '/ˈfeɪməs/', meaning: '著名的', category: '形容', level: 'L3' },
  { id: 'e289', word: 'Lucky', phonetic: '/ˈlʌki/', meaning: '幸运的', category: '形容', level: 'L3' },
  { id: 'e290', word: 'Successful', phonetic: '/səkˈsesfl/', meaning: '成功的', category: '形容', level: 'L3' },
  { id: 'e291', word: 'Careful', phonetic: '/ˈkerfl/', meaning: '小心的', category: '形容', level: 'L3' },
  { id: 'e292', word: 'Helpful', phonetic: '/ˈhelpfl/', meaning: '有帮助的', category: '形容', level: 'L3' },
  { id: 'e293', word: 'Wonderful', phonetic: '/ˈwʌndərfl/', meaning: '精彩的', category: '形容', level: 'L3' },
  { id: 'e294', word: 'Terrible', phonetic: '/ˈterəbl/', meaning: '糟糕的', category: '形容', level: 'L3' },
  { id: 'e295', word: 'Perfect', phonetic: '/ˈpɜːrfɪkt/', meaning: '完美的', category: '形容', level: 'L3' },

  // 更多名词
  { id: 'e296', word: 'Language', phonetic: '/ˈlæŋɡwɪdʒ/', meaning: '语言', category: '名词', level: 'L3' },
  { id: 'e297', word: 'Country', phonetic: '/ˈkʌntri/', meaning: '国家', category: '名词', level: 'L3' },
  { id: 'e298', word: 'City', phonetic: '/ˈsɪti/', meaning: '城市', category: '名词', level: 'L3' },
  { id: 'e299', word: 'Village', phonetic: '/ˈvɪlɪdʒ/', meaning: '村庄', category: '名词', level: 'L3' },
  { id: 'e300', word: 'Street', phonetic: '/striːt/', meaning: '街道', category: '名词', level: 'L3' },
  { id: 'e301', word: 'Bridge', phonetic: '/brɪdʒ/', meaning: '桥', category: '名词', level: 'L3' },
  { id: 'e302', word: 'Building', phonetic: '/ˈbɪldɪŋ/', meaning: '建筑物', category: '名词', level: 'L3' },
  { id: 'e303', word: 'Church', phonetic: '/tʃɜːrtʃ/', meaning: '教堂', category: '名词', level: 'L3' },
  { id: 'e304', word: 'Museum', phonetic: '/mjuˈziːəm/', meaning: '博物馆', category: '名词', level: 'L3' },
  { id: 'e305', word: 'University', phonetic: '/ˌjuːnɪˈvɜːrsəti/', meaning: '大学', category: '名词', level: 'L3' },
  { id: 'e306', word: 'Experience', phonetic: '/ɪkˈspɪəriəns/', meaning: '经验/经历', category: '名词', level: 'L3' },
  { id: 'e307', word: 'Feeling', phonetic: '/ˈfiːlɪŋ/', meaning: '感觉', category: '名词', level: 'L3' },
  { id: 'e308', word: 'Thought', phonetic: '/θɔːt/', meaning: '想法', category: '名词', level: 'L3' },
  { id: 'e309', word: 'Reason', phonetic: '/ˈriːzn/', meaning: '原因', category: '名词', level: 'L3' },
  { id: 'e310', word: 'Result', phonetic: '/rɪˈzʌlt/', meaning: '结果', category: '名词', level: 'L3' },
  { id: 'e311', word: 'Example', phonetic: '/ɪɡˈzɑːmpl/', meaning: '例子', category: '名词', level: 'L3' },
  { id: 'e312', word: 'Problem', phonetic: '/ˈprɒbləm/', meaning: '问题', category: '名词', level: 'L3' },
  { id: 'e313', word: 'Answer', phonetic: '/ˈænsər/', meaning: '答案', category: '名词', level: 'L3' },
  { id: 'e314', word: 'Question', phonetic: '/ˈkwestʃən/', meaning: '问题', category: '名词', level: 'L3' },
  { id: 'e315', word: 'Idea', phonetic: '/aɪˈdɪə/', meaning: '主意', category: '名词', level: 'L3' },
  { id: 'e316', word: 'Plan', phonetic: '/plæn/', meaning: '计划', category: '名词', level: 'L3' },
  { id: 'e317', word: 'Decision', phonetic: '/dɪˈsɪʒn/', meaning: '决定', category: '名词', level: 'L3' },
  { id: 'e318', word: 'Chance', phonetic: '/tʃæns/', meaning: '机会', category: '名词', level: 'L3' },
  { id: 'e319', word: 'Choice', phonetic: '/tʃɔɪs/', meaning: '选择', category: '名词', level: 'L3' },
  { id: 'e320', word: 'Change', phonetic: '/tʃeɪndʒ/', meaning: '变化', category: '名词', level: 'L3' },
  { id: 'e321', word: 'Dream', phonetic: '/driːm/', meaning: '梦想', category: '名词', level: 'L3' },
  { id: 'e322', word: 'Goal', phonetic: '/ɡoʊl/', meaning: '目标', category: '名词', level: 'L3' },
  { id: 'e323', word: 'Success', phonetic: '/səkˈses/', meaning: '成功', category: '名词', level: 'L3' },
  { id: 'e324', word: 'Failure', phonetic: '/ˈfeɪljər/', meaning: '失败', category: '名词', level: 'L3' },
  { id: 'e325', word: 'Life', phonetic: '/laɪf/', meaning: '生活/生命', category: '名词', level: 'L3' },
  { id: 'e326', word: 'Death', phonetic: '/deθ/', meaning: '死亡', category: '名词', level: 'L3' },
  { id: 'e327', word: 'Health', phonetic: '/helθ/', meaning: '健康', category: '名词', level: 'L3' },
  { id: 'e328', word: 'Future', phonetic: '/ˈfjuːtʃər/', meaning: '未来', category: '名词', level: 'L3' },
  { id: 'e329', word: 'Past', phonetic: '/pæst/', meaning: '过去', category: '名词', level: 'L3' },
  { id: 'e330', word: 'Present', phonetic: '/ˈpreznt/', meaning: '现在/礼物', category: '名词', level: 'L3' }
]
