/**
 * 英语单词 Level 5 - 高中
 * 词汇：学术、社会、经济、文化、高级动词/形容词
 */
module.exports = [
  // 学术
  { id: 'e321', word: 'Research', phonetic: '/rɪˈsɜːrtʃ/', meaning: '研究', category: '学术', level: 'L5' },
  { id: 'e322', word: 'Theory', phonetic: '/ˈθɪəri/', meaning: '理论', category: '学术', level: 'L5' },
  { id: 'e323', word: 'Experiment', phonetic: '/ɪkˈsperɪmənt/', meaning: '实验', category: '学术', level: 'L5' },
  { id: 'e324', word: 'Discovery', phonetic: '/dɪˈskʌvəri/', meaning: '发现', category: '学术', level: 'L5' },
  { id: 'e325', word: 'Invention', phonetic: '/ɪnˈvenʃn/', meaning: '发明', category: '学术', level: 'L5' },
  { id: 'e326', word: 'Technology', phonetic: '/tekˈnɒlədʒi/', meaning: '技术', category: '学术', level: 'L5' },
  { id: 'e327', word: 'Science', phonetic: '/ˈsaɪəns/', meaning: '科学', category: '学术', level: 'L5' },
  { id: 'e328', word: 'History', phonetic: '/ˈhɪstri/', meaning: '历史', category: '学术', level: 'L5' },
  { id: 'e329', word: 'Geography', phonetic: '/dʒiˈɒɡrəfi/', meaning: '地理', category: '学术', level: 'L5' },
  { id: 'e330', word: 'Mathematics', phonetic: '/ˌmæθəˈmætɪks/', meaning: '数学', category: '学术', level: 'L5' },
  { id: 'e331', word: 'Literature', phonetic: '/ˈlɪtrətʃər/', meaning: '文学', category: '学术', level: 'L5' },
  { id: 'e332', word: 'Philosophy', phonetic: '/fɪˈlɒsəfi/', meaning: '哲学', category: '学术', level: 'L5' },
  { id: 'e333', word: 'Psychology', phonetic: '/saɪˈkɒlədʒi/', meaning: '心理学', category: '学术', level: 'L5' },
  { id: 'e334', word: 'Economy', phonetic: '/ɪˈkɒnəmi/', meaning: '经济', category: '学术', level: 'L5' },
  { id: 'e335', word: 'Politics', phonetic: '/ˈpɒlətɪks/', meaning: '政治', category: '学术', level: 'L5' },

  // 社会
  { id: 'e336', word: 'Society', phonetic: '/səˈsaɪəti/', meaning: '社会', category: '社会', level: 'L5' },
  { id: 'e337', word: 'Culture', phonetic: '/ˈkʌltʃər/', meaning: '文化', category: '社会', level: 'L5' },
  { id: 'e338', word: 'Tradition', phonetic: '/trəˈdɪʃn/', meaning: '传统', category: '社会', level: 'L5' },
  { id: 'e339', word: 'Custom', phonetic: '/ˈkʌstəm/', meaning: '习俗', category: '社会', level: 'L5' },
  { id: 'e340', word: 'Government', phonetic: '/ˈɡʌvərnmənt/', meaning: '政府', category: '社会', level: 'L5' },
  { id: 'e341', word: 'Law', phonetic: '/lɔː/', meaning: '法律', category: '社会', level: 'L5' },
  { id: 'e342', word: 'Right', phonetic: '/raɪt/', meaning: '权利', category: '社会', level: 'L5' },
  { id: 'e343', word: 'Duty', phonetic: '/ˈdjuːti/', meaning: '责任', category: '社会', level: 'L5' },
  { id: 'e344', word: 'Freedom', phonetic: '/ˈfriːdəm/', meaning: '自由', category: '社会', level: 'L5' },
  { id: 'e345', word: 'Peace', phonetic: '/piːs/', meaning: '和平', category: '社会', level: 'L5' },
  { id: 'e346', word: 'War', phonetic: '/wɔːr/', meaning: '战争', category: '社会', level: 'L5' },
  { id: 'e347', word: 'Justice', phonetic: '/ˈdʒʌstɪs/', meaning: '正义', category: '社会', level: 'L5' },
  { id: 'e348', word: 'Equality', phonetic: '/ɪˈkwɒləti/', meaning: '平等', category: '社会', level: 'L5' },
  { id: 'e349', word: 'Citizen', phonetic: '/ˈsɪtɪzn/', meaning: '公民', category: '社会', level: 'L5' },
  { id: 'e350', word: 'Community', phonetic: '/kəˈmjuːnəti/', meaning: '社区', category: '社会', level: 'L5' },

  // 经济
  { id: 'e351', word: 'Business', phonetic: '/ˈbɪznəs/', meaning: '商业', category: '经济', level: 'L5' },
  { id: 'e352', word: 'Company', phonetic: '/ˈkʌmpəni/', meaning: '公司', category: '经济', level: 'L5' },
  { id: 'e353', word: 'Market', phonetic: '/ˈmɑːrkɪt/', meaning: '市场', category: '经济', level: 'L5' },
  { id: 'e354', word: 'Price', phonetic: '/praɪs/', meaning: '价格', category: '经济', level: 'L5' },
  { id: 'e355', word: 'Profit', phonetic: '/ˈprɒfɪt/', meaning: '利润', category: '经济', level: 'L5' },
  { id: 'e356', word: 'Investment', phonetic: '/ɪnˈvestmənt/', meaning: '投资', category: '经济', level: 'L5' },
  { id: 'e357', word: 'Trade', phonetic: '/treɪd/', meaning: '贸易', category: '经济', level: 'L5' },
  { id: 'e358', word: 'Import', phonetic: '/ˈɪmpɔːrt/', meaning: '进口', category: '经济', level: 'L5' },
  { id: 'e359', word: 'Export', phonetic: '/ˈekspɔːrt/', meaning: '出口', category: '经济', level: 'L5' },
  { id: 'e360', word: 'Salary', phonetic: '/ˈsæləri/', meaning: '工资', category: '经济', level: 'L5' },

  // 高级动词
  { id: 'e361', word: 'Achieve', phonetic: '/əˈtʃiːv/', meaning: '实现/达到', category: '动词', level: 'L5' },
  { id: 'e362', word: 'Analyze', phonetic: '/ˈænəlaɪz/', meaning: '分析', category: '动词', level: 'L5' },
  { id: 'e363', word: 'Compare', phonetic: '/kəmˈper/', meaning: '比较', category: '动词', level: 'L5' },
  { id: 'e364', word: 'Conclude', phonetic: '/kənˈkluːd/', meaning: '总结', category: '动词', level: 'L5' },
  { id: 'e365', word: 'Consider', phonetic: '/kənˈsɪdər/', meaning: '考虑', category: '动词', level: 'L5' },
  { id: 'e366', word: 'Contribute', phonetic: '/kənˈtrɪbjuːt/', meaning: '贡献', category: '动词', level: 'L5' },
  { id: 'e367', word: 'Describe', phonetic: '/dɪˈskraɪb/', meaning: '描述', category: '动词', level: 'L5' },
  { id: 'e368', word: 'Develop', phonetic: '/dɪˈveləp/', meaning: '发展', category: '动词', level: 'L5' },
  { id: 'e369', word: 'Discover', phonetic: '/dɪˈskʌvər/', meaning: '发现', category: '动词', level: 'L5' },
  { id: 'e370', word: 'Establish', phonetic: '/ɪˈstæblɪʃ/', meaning: '建立', category: '动词', level: 'L5' },
  { id: 'e371', word: 'Improve', phonetic: '/ɪmˈpruːv/', meaning: '改善', category: '动词', level: 'L5' },
  { id: 'e372', word: 'Influence', phonetic: '/ˈɪnfluəns/', meaning: '影响', category: '动词', level: 'L5' },
  { id: 'e373', word: 'Maintain', phonetic: '/meɪnˈteɪn/', meaning: '维持', category: '动词', level: 'L5' },
  { id: 'e374', word: 'Observe', phonetic: '/əbˈzɜːrv/', meaning: '观察', category: '动词', level: 'L5' },
  { id: 'e375', word: 'Recognize', phonetic: '/ˈrekəɡnaɪz/', meaning: '认识/承认', category: '动词', level: 'L5' },
  { id: 'e376', word: 'Reflect', phonetic: '/rɪˈflekt/', meaning: '反映/反思', category: '动词', level: 'L5' },
  { id: 'e377', word: 'Respond', phonetic: '/rɪˈspɒnd/', meaning: '回应', category: '动词', level: 'L5' },
  { id: 'e378', word: 'Suggest', phonetic: '/səˈdʒest/', meaning: '建议', category: '动词', level: 'L5' },
  { id: 'e379', word: 'Support', phonetic: '/səˈpɔːrt/', meaning: '支持', category: '动词', level: 'L5' },
  { id: 'e380', word: 'Transform', phonetic: '/trænsˈfɔːrm/', meaning: '转变', category: '动词', level: 'L5' },

  // 高级形容词
  { id: 'e381', word: 'Ancient', phonetic: '/ˈeɪnʃənt/', meaning: '古代的', category: '形容', level: 'L5' },
  { id: 'e382', word: 'Brilliant', phonetic: '/ˈbrɪliənt/', meaning: '杰出的', category: '形容', level: 'L5' },
  { id: 'e383', word: 'Complex', phonetic: '/ˈkɒmpleks/', meaning: '复杂的', category: '形容', level: 'L5' },
  { id: 'e384', word: 'Creative', phonetic: '/kriˈeɪtɪv/', meaning: '有创造力的', category: '形容', level: 'L5' },
  { id: 'e385', word: 'Crucial', phonetic: '/ˈkruːʃl/', meaning: '关键的', category: '形容', level: 'L5' },
  { id: 'e386', word: 'Effective', phonetic: '/ɪˈfektɪv/', meaning: '有效的', category: '形容', level: 'L5' },
  { id: 'e387', word: 'Efficient', phonetic: '/ɪˈfɪʃnt/', meaning: '高效的', category: '形容', level: 'L5' },
  { id: 'e388', word: 'Essential', phonetic: '/ɪˈsenʃl/', meaning: '必要的', category: '形容', level: 'L5' },
  { id: 'e389', word: 'Flexible', phonetic: '/ˈfleksəbl/', meaning: '灵活的', category: '形容', level: 'L5' },
  { id: 'e390', word: 'Generous', phonetic: '/ˈdʒenərəs/', meaning: '慷慨的', category: '形容', level: 'L5' },
  { id: 'e391', word: 'Independent', phonetic: '/ˌɪndɪˈpendənt/', meaning: '独立的', category: '形容', level: 'L5' },
  { id: 'e392', word: 'Innovative', phonetic: '/ˈɪnəveɪtɪv/', meaning: '创新的', category: '形容', level: 'L5' },
  { id: 'e393', word: 'Logical', phonetic: '/ˈlɒdʒɪkl/', meaning: '逻辑的', category: '形容', level: 'L5' },
  { id: 'e394', word: 'Obvious', phonetic: '/ˈɒbviəs/', meaning: '明显的', category: '形容', level: 'L5' },
  { id: 'e395', word: 'Potential', phonetic: '/pəˈtenʃl/', meaning: '潜在的', category: '形容', level: 'L5' },
  { id: 'e396', word: 'Relevant', phonetic: '/ˈreləvənt/', meaning: '相关的', category: '形容', level: 'L5' },
  { id: 'e397', word: 'Significant', phonetic: '/sɪɡˈnɪfɪkənt/', meaning: '重要的', category: '形容', level: 'L5' },
  { id: 'e398', word: 'Specific', phonetic: '/spəˈsɪfɪk/', meaning: '具体的', category: '形容', level: 'L5' },
  { id: 'e399', word: 'Sufficient', phonetic: '/səˈfɪʃnt/', meaning: '足够的', category: '形容', level: 'L5' },
  { id: 'e400', word: 'Unique', phonetic: '/juˈniːk/', meaning: '独特的', category: '形容', level: 'L5' }
]
